## Lendo JSON

In [4]:
#Lendo os dados do Json

path_json = '/home/fe/Documentos/Git/Engenharia-de-Dados/Pipeline Dados/Data Raw/dados_empresaA.json'
with open(path_json, 'r') as file:
    dados = (file.readline())

dados

'[{"Nome do Produto":"Blush em p\\u00f3","Categoria do Produto":"Eletrodom\\u00e9sticos","Pre\\u00e7o do Produto (R$)":79.41,"Quantidade em Estoque":7,"Filial":"Filial 7"},\n'

In [6]:
import json

with open(path_json, 'r') as file:
    dados_json = json.load(file)
#Primeiro registro
dados_json[0]

{'Nome do Produto': 'Blush em pó',
 'Categoria do Produto': 'Eletrodomésticos',
 'Preço do Produto (R$)': 79.41,
 'Quantidade em Estoque': 7,
 'Filial': 'Filial 7'}

### Lendo o CSV

In [9]:
path_csv = '/home/fe/Documentos/Git/Engenharia-de-Dados/Pipeline Dados/Data Raw/dados_empresaB.csv'
with open(path_csv, 'r') as file:
    dados_csv = file.readlines()
dados_csv[1]

'Lápis de sobrancelha,Roupas,55.17,62,Filial 1,2023-04-13 18:58:06.794203\n'

In [13]:
import csv

dados_csv = []
path_csv = '/home/fe/Documentos/Git/Engenharia-de-Dados/Pipeline Dados/Data Raw/dados_empresaB.csv'
with open(path_csv, 'r') as file:
    spamreader = csv.reader(file, delimiter=",")
    for linha in spamreader:
        dados_csv.append(linha)
dados_csv

[['Nome do Item',
  'Classificação do Produto',
  'Valor em Reais (R$)',
  'Quantidade em Estoque',
  'Nome da Loja',
  'Data da Venda'],
 ['Lápis de sobrancelha',
  'Roupas',
  '55.17',
  '62',
  'Filial 1',
  '2023-04-13 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '74.15',
  '48',
  'Filial 9',
  '2023-06-03 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '54.86',
  '36',
  'Filial 5',
  '2023-06-08 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '91.29',
  '1',
  'Filial 8',
  '2023-02-27 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '44.65',
  '52',
  'Filial 2',
  '2022-09-05 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '5.22',
  '85',
  'Filial 3',
  '2022-09-11 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '1.08',
  '31',
  'Filial 6',
  '2023-02-08 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '56.22',
  '76',
  'Filial 5',
  '2022-12-08 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '94.01',
  '7',
  'Filial 2',
  '2023-07-18 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Alimentos',
  '51.38',
  '4',
  'Filial 10',
  '2023-06-19 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '5.59',
  '82',
  'Filial 10',
  '2023-07-19 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '2.65',
  '8',
  'Filial 3',
  '2023-05-24 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '68.62',
  '6',
  'Filial 1',
  '2023-01-24 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '80.94',
  '70',
  'Filial 6',
  '2023-06-07 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '26.79',
  '86',
  'Filial 9',
  '2023-01-10 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '55.08',
  '14',
  'Filial 5',
  '2023-02-09 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '51.34',
  '13',
  'Filial 2',
  '2022-10-24 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '31.07',
  '45',
  'Filial 8',
  '2023-03-06 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '78.94',
  '44',
  'Filial 7',
  '2022-11-12 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '41.15',
  '91',
  'Filial 9',
  '2023-02-03 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '44.47',
  '39',
  'Filial 4',
  '2023-07-31 18:58:06.794203'],
 ['Sombra de olhos',
  'Roupas',
  '32.8',
  '23',
  'Filial 3',
  '2023-06-07 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '90.62',
  '70',
  'Filial 3',
  '2022-10-31 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '66.56',
  '89',
  'Filial 1',
  '2023-03-04 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '57.56',
  '77',
  'Filial 8',
  '2023-01-27 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '40.92',
  '13',
  'Filial 3',
  '2023-04-25 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '65.96',
  '73',
  'Filial 10',
  '2022-09-20 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '87.64',
  '25',
  'Filial 5',
  '2023-03-09 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '61.21',
  '22',
  'Filial 3',
  '2023-02-06 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '12.77',
  '57',
  'Filial 8',
  '2023-05-15 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '86.67',
  '61',
  'Filial 10',
  '2023-07-06 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '26.87',
  '56',
  'Filial 6',
  '2023-07-24 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '83.86',
  '33',
  'Filial 2',
  '2023-05-02 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '89.13',
  '49',
  'Filial 3',
  '2023-07-07 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '12.08',
  '87',
  'Filial 2',
  '2023-04-15 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '73.5',
  '67',
  'Filial 4',
  '2022-11-07 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '90.34',
  '76',
  'Filial 2',
  '2023-06-16 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '5.74',
  '1',
  'Filial 4',
  '2022-12-15 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '47.47',
  '62',
  'Filial 3',
  '2023-02-01 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '87.52',
  '43',
  'Filial 9',
  '2023-08-22 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '14.57',
  '72',
  'Filial 10',
  '2023-05-20 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '69.69',
  '9',
  'Filial 8',
  '2023-02-03 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '62.96',
  '12',
  'Filial 5',
  '2023-05-02 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '52.49',
  '57',
  'Filial 1',
  '2023-03-10 18:58:06.794203'],
 ['Sombra de olhos',
  'Roupas',
  '85.51',
  '5',
  'Filial 5',
  '2023-04-17 18:58:06.794203'],
 ['Base líquida',
  'Roupas',
  '8.72',
  '48',
  'Filial 5',
  '2023-05-16 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '78.58',
  '89',
  'Filial 10',
  '2022-12-16 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '23.8',
  '28',
  'Filial 9',
  '2022-10-14 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrodomésticos',
  '36.96',
  '5',
  'Filial 3',
  '2022-11-05 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '13.84',
  '2',
  'Filial 6',
  '2023-04-30 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '23.45',
  '69',
  'Filial 7',
  '2023-04-28 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '31.88',
  '19',
  'Filial 3',
  '2023-02-15 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '73.9',
  '83',
  'Filial 3',
  '2023-07-02 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '48.62',
  '32',
  'Filial 5',
  '2023-05-27 18:58:06.794203'],
 ['Batom matte',
  'Eletrodomésticos',
  '46.32',
  '52',
  'Filial 8',
  '2023-04-12 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '6.9',
  '10',
  'Filial 4',
  '2023-03-23 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '26.51',
  '10',
  'Filial 2',
  '2022-10-27 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '37.52',
  '55',
  'Filial 9',
  '2023-02-13 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '18.37',
  '29',
  'Filial 9',
  '2023-01-01 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '75.04',
  '90',
  'Filial 3',
  '2023-08-29 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '9.59',
  '46',
  'Filial 8',
  '2023-03-31 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '84.24',
  '27',
  'Filial 5',
  '2023-03-07 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '22.41',
  '97',
  'Filial 2',
  '2022-09-11 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '18.03',
  '7',
  'Filial 10',
  '2023-01-26 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '56.88',
  '49',
  'Filial 2',
  '2023-02-01 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '71.07',
  '10',
  'Filial 4',
  '2023-01-01 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '80.43',
  '2',
  'Filial 10',
  '2023-08-03 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '67.95',
  '50',
  'Filial 10',
  '2022-10-06 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '15.85',
  '89',
  'Filial 9',
  '2023-01-09 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '39.86',
  '31',
  'Filial 7',
  '2023-07-02 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '14.98',
  '40',
  'Filial 3',
  '2023-06-04 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '6.9',
  '91',
  'Filial 9',
  '2023-02-23 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '57.28',
  '10',
  'Filial 3',
  '2023-07-31 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '11.71',
  '77',
  'Filial 6',
  '2022-11-18 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '60.0',
  '23',
  'Filial 2',
  '2022-11-19 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '94.51',
  '72',
  'Filial 8',
  '2023-01-14 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '86.96',
  '89',
  'Filial 7',
  '2022-11-25 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '36.37',
  '50',
  'Filial 1',
  '2022-09-29 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '9.36',
  '72',
  'Filial 5',
  '2023-07-21 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '43.3',
  '78',
  'Filial 6',
  '2023-02-11 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '75.34',
  '75',
  'Filial 1',
  '2023-01-02 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '40.39',
  '84',
  'Filial 10',
  '2022-12-16 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '11.05',
  '15',
  'Filial 2',
  '2022-12-26 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '39.21',
  '26',
  'Filial 10',
  '2022-12-19 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '48.01',
  '46',
  'Filial 8',
  '2023-02-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '1.65',
  '79',
  'Filial 8',
  '2022-10-21 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '43.61',
  '75',
  'Filial 2',
  '2022-09-26 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '75.25',
  '11',
  'Filial 3',
  '2023-08-04 18:58:06.794203'],
 ['Máscara de cílios',
  'Alimentos',
  '55.73',
  '25',
  'Filial 2',
  '2023-06-06 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '11.96',
  '7',
  'Filial 6',
  '2023-03-25 18:58:06.794203'],
 ['Batom líquido',
  'Alimentos',
  '84.91',
  '88',
  'Filial 6',
  '2022-09-22 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '83.6',
  '47',
  'Filial 2',
  '2023-06-23 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrodomésticos',
  '87.64',
  '22',
  'Filial 7',
  '2023-08-17 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '79.79',
  '98',
  'Filial 5',
  '2023-06-06 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '18.36',
  '67',
  'Filial 5',
  '2022-09-12 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '40.28',
  '67',
  'Filial 3',
  '2023-03-03 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '41.92',
  '79',
  'Filial 4',
  '2023-01-29 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '48.15',
  '82',
  'Filial 6',
  '2022-12-03 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '30.29',
  '96',
  'Filial 6',
  '2023-02-27 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '98.66',
  '86',
  'Filial 3',
  '2023-07-06 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '61.41',
  '14',
  'Filial 5',
  '2023-07-06 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '99.22',
  '4',
  'Filial 7',
  '2022-11-24 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '61.0',
  '28',
  'Filial 10',
  '2022-12-24 18:58:06.794203'],
 ['Blush em pó',
  'Eletrônicos',
  '18.86',
  '45',
  'Filial 9',
  '2023-05-14 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '33.76',
  '97',
  'Filial 5',
  '2023-04-23 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '67.41',
  '3',
  'Filial 9',
  '2023-01-17 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '58.3',
  '93',
  'Filial 3',
  '2022-10-22 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '57.95',
  '63',
  'Filial 9',
  '2022-10-28 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '66.9',
  '63',
  'Filial 2',
  '2023-03-13 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '35.55',
  '48',
  'Filial 3',
  '2023-03-08 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '51.94',
  '55',
  'Filial 7',
  '2023-04-28 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '86.0',
  '54',
  'Filial 7',
  '2023-08-06 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '73.84',
  '27',
  'Filial 3',
  '2023-02-19 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '34.84',
  '55',
  'Filial 5',
  '2022-11-01 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '41.5',
  '72',
  'Filial 6',
  '2023-03-18 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '92.31',
  '50',
  'Filial 6',
  '2023-03-10 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '20.64',
  '18',
  'Filial 2',
  '2022-10-09 18:58:06.794203'],
 ['Batom líquido',
  'Alimentos',
  '94.09',
  '81',
  'Filial 7',
  '2022-12-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '60.69',
  '47',
  'Filial 5',
  '2022-11-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '11.55',
  '5',
  'Filial 1',
  '2022-11-21 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '95.51',
  '56',
  'Filial 8',
  '2022-11-21 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '89.33',
  '8',
  'Filial 8',
  '2023-06-19 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '49.56',
  '38',
  'Filial 9',
  '2022-11-25 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '98.97',
  '30',
  'Filial 4',
  '2023-08-30 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '89.56',
  '85',
  'Filial 3',
  '2022-09-10 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '77.81',
  '20',
  'Filial 3',
  '2023-01-20 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '75.06',
  '24',
  'Filial 3',
  '2023-06-21 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '88.5',
  '8',
  'Filial 8',
  '2023-09-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '17.84',
  '59',
  'Filial 1',
  '2022-09-30 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '64.88',
  '81',
  'Filial 8',
  '2023-04-02 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '69.6',
  '25',
  'Filial 4',
  '2023-03-19 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '24.02',
  '85',
  'Filial 2',
  '2022-12-27 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '67.19',
  '63',
  'Filial 2',
  '2023-01-13 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '67.23',
  '28',
  'Filial 6',
  '2022-10-30 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '86.85',
  '40',
  'Filial 9',
  '2022-10-07 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '41.75',
  '98',
  'Filial 9',
  '2023-07-25 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '52.42',
  '38',
  'Filial 3',
  '2022-11-20 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '17.13',
  '99',
  'Filial 9',
  '2022-12-04 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '22.72',
  '51',
  'Filial 7',
  '2023-06-28 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '35.28',
  '69',
  'Filial 8',
  '2023-02-23 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '46.76',
  '63',
  'Filial 8',
  '2023-07-02 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '41.45',
  '74',
  'Filial 2',
  '2023-02-02 18:58:06.794203'],
 ['Base líquida',
  'Roupas',
  '93.51',
  '69',
  'Filial 4',
  '2023-03-12 18:58:06.794203'],
 ['Blush em pó',
  'Eletrônicos',
  '88.99',
  '17',
  'Filial 6',
  '2023-06-22 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '1.1',
  '22',
  'Filial 10',
  '2022-10-23 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '58.94',
  '23',
  'Filial 9',
  '2023-04-17 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '76.57',
  '87',
  'Filial 8',
  '2022-12-05 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '22.91',
  '49',
  'Filial 9',
  '2023-07-28 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '28.89',
  '33',
  'Filial 6',
  '2022-09-27 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '33.57',
  '22',
  'Filial 9',
  '2022-09-05 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '4.12',
  '46',
  'Filial 2',
  '2023-08-07 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '73.13',
  '66',
  'Filial 9',
  '2023-04-23 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '1.69',
  '21',
  'Filial 3',
  '2022-11-20 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '27.18',
  '24',
  'Filial 8',
  '2023-02-01 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '94.47',
  '77',
  'Filial 8',
  '2023-07-03 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '67.19',
  '76',
  'Filial 1',
  '2023-04-10 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '92.72',
  '62',
  'Filial 4',
  '2022-12-08 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '78.29',
  '67',
  'Filial 5',
  '2022-10-09 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '83.18',
  '15',
  'Filial 1',
  '2022-12-21 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '75.77',
  '26',
  'Filial 9',
  '2023-03-07 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '81.71',
  '90',
  'Filial 4',
  '2023-07-25 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '20.73',
  '49',
  'Filial 6',
  '2023-08-11 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '57.12',
  '10',
  'Filial 6',
  '2023-08-11 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '29.61',
  '15',
  'Filial 5',
  '2023-01-24 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '71.75',
  '31',
  'Filial 10',
  '2023-07-26 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '84.33',
  '26',
  'Filial 6',
  '2022-11-29 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '17.9',
  '33',
  'Filial 7',
  '2023-01-28 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '62.61',
  '34',
  'Filial 6',
  '2023-04-13 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '9.21',
  '95',
  'Filial 10',
  '2023-04-29 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '21.71',
  '77',
  'Filial 2',
  '2022-11-20 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '34.76',
  '51',
  'Filial 4',
  '2023-04-09 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '61.77',
  '41',
  'Filial 3',
  '2023-08-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '29.04',
  '21',
  'Filial 1',
  '2023-04-10 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '32.33',
  '6',
  'Filial 8',
  '2023-05-06 18:58:06.794203'],
 ['Batom matte',
  'Eletrodomésticos',
  '25.68',
  '33',
  'Filial 3',
  '2023-05-24 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '6.8',
  '8',
  'Filial 2',
  '2023-01-19 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '85.55',
  '33',
  'Filial 2',
  '2022-10-30 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '61.23',
  '80',
  'Filial 6',
  '2023-04-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '7.43',
  '18',
  'Filial 1',
  '2022-10-27 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '92.77',
  '18',
  'Filial 6',
  '2023-02-05 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '70.44',
  '79',
  'Filial 5',
  '2023-02-19 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '98.45',
  '14',
  'Filial 7',
  '2022-11-27 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '12.18',
  '59',
  'Filial 10',
  '2023-07-12 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '71.31',
  '84',
  'Filial 2',
  '2023-07-19 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '54.71',
  '62',
  'Filial 5',
  '2023-06-02 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '45.12',
  '10',
  'Filial 3',
  '2023-04-25 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '32.26',
  '60',
  'Filial 8',
  '2023-03-25 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '86.78',
  '24',
  'Filial 6',
  '2022-12-13 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '71.86',
  '26',
  'Filial 10',
  '2023-06-02 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '45.38',
  '41',
  'Filial 5',
  '2023-05-25 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '53.76',
  '27',
  'Filial 4',
  '2023-03-05 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '7.41',
  '93',
  'Filial 6',
  '2023-01-18 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '68.97',
  '79',
  'Filial 3',
  '2023-03-15 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '10.5',
  '80',
  'Filial 6',
  '2023-07-26 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '67.79',
  '19',
  'Filial 5',
  '2023-09-05 18:58:06.794203'],

### Transformando no mesmo modelo

In [15]:
#Passando o csv para o mesmo formato do json
dados_csv = []
with open(path_csv, 'r') as file:
    spamreader = csv.DictReader(file, delimiter=",")
    for linha in spamreader:
        dados_csv.append(linha)
dados_csv

[{'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '55.17',
  'Quantidade em Estoque': '62',
  'Nome da Loja': 'Filial 1',
  'Data da Venda': '2023-04-13 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '74.15',
  'Quantidade em Estoque': '48',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-06-03 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '54.86',
  'Quantidade em Estoque': '36',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-06-08 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '91.29',
  'Quantidade em Estoque': '1',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-02-27 18:58:06.794203'},
 {'Nome do Item': 'Batom líquido',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '44.65',
  'Quantidade em Estoque': '52',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2022-09-05 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '5.22',
  'Quantidade em Estoque': '85',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2022-09-11 18:58:06.794203'},
 {'Nome do Item': 'Máscara de cílios',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '1.08',
  'Quantidade em Estoque': '31',
  'Nome da Loja': 'Filial 6',
  'Data da Venda': '2023-02-08 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '56.22',
  'Quantidade em Estoque': '76',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2022-12-08 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '94.01',
  'Quantidade em Estoque': '7',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2023-07-18 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '51.38',
  'Quantidade em Estoque': '4',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2023-06-19 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '5.59',
  'Quantidade em Estoque': '82',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2023-07-19 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '2.65',
  'Quantidade em Estoque': '8',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-05-24 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '68.62',
  'Quantidade em Estoque': '6',
  'Nome da Loja': 'Filial 1',
  'Data da Venda': '2023-01-24 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '80.94',
  'Quantidade em Estoque': '70',
  'Nome da Loja': 'Filial 6',
  'Data da Venda': '2023-06-07 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '26.79',
  'Quantidade em Estoque': '86',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-01-10 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '55.08',
  'Quantidade em Estoque': '14',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-02-09 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '51.34',
  'Quantidade em Estoque': '13',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2022-10-24 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '31.07',
  'Quantidade em Estoque': '45',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-03-06 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '78.94',
  'Quantidade em Estoque': '44',
  'Nome da Loja': 'Filial 7',
  'Data da Venda': '2022-11-12 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '41.15',
  'Quantidade em Estoque': '91',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-02-03 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '44.47',
  'Quantidade em Estoque': '39',
  'Nome da Loja': 'Filial 4',
  'Data da Venda': '2023-07-31 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '32.8',
  'Quantidade em Estoque': '23',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-06-07 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '90.62',
  'Quantidade em Estoque': '70',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2022-10-31 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '66.56',
  'Quantidade em Estoque': '89',
  'Nome da Loja': 'Filial 1',
  'Data da Venda': '2023-03-04 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '57.56',
  'Quantidade em Estoque': '77',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-01-27 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '40.92',
  'Quantidade em Estoque': '13',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-04-25 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '65.96',
  'Quantidade em Estoque': '73',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2022-09-20 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '87.64',
  'Quantidade em Estoque': '25',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-03-09 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '61.21',
  'Quantidade em Estoque': '22',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-02-06 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '12.77',
  'Quantidade em Estoque': '57',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-05-15 18:58:06.794203'},
 {'Nome do Item': 'Blush em pó',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '86.67',
  'Quantidade em Estoque': '61',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2023-07-06 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '26.87',
  'Quantidade em Estoque': '56',
  'Nome da Loja': 'Filial 6',
  'Data da Venda': '2023-07-24 18:58:06.794203'},
 {'Nome do Item': 'Batom líquido',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '83.86',
  'Quantidade em Estoque': '33',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2023-05-02 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '89.13',
  'Quantidade em Estoque': '49',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-07-07 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '12.08',
  'Quantidade em Estoque': '87',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2023-04-15 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '73.5',
  'Quantidade em Estoque': '67',
  'Nome da Loja': 'Filial 4',
  'Data da Venda': '2022-11-07 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '90.34',
  'Quantidade em Estoque': '76',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2023-06-16 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '5.74',
  'Quantidade em Estoque': '1',
  'Nome da Loja': 'Filial 4',
  'Data da Venda': '2022-12-15 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '47.47',
  'Quantidade em Estoque': '62',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-02-01 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '87.52',
  'Quantidade em Estoque': '43',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-08-22 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '14.57',
  'Quantidade em Estoque': '72',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2023-05-20 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '69.69',
  'Quantidade em Estoque': '9',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-02-03 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '62.96',
  'Quantidade em Estoque': '12',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-05-02 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '52.49',
  'Quantidade em Estoque': '57',
  'Nome da Loja': 'Filial 1',
  'Data da Venda': '2023-03-10 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '85.51',
  'Quantidade em Estoque': '5',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-04-17 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '8.72',
  'Quantidade em Estoque': '48',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-05-16 18:58:06.794203'},
 {'Nome do Item': 'Batom líquido',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '78.58',
  'Quantidade em Estoque': '89',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2022-12-16 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '23.8',
  'Quantidade em Estoque': '28',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2022-10-14 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '36.96',
  'Quantidade em Estoque': '5',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2022-11-05 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '13.84',
  'Quantidade em Estoque': '2',
  'Nome da Loja': 'Filial 6',
  'Data da Venda': '2023-04-30 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '23.45',
  'Quantidade em Estoque': '69',
  'Nome da Loja': 'Filial 7',
  'Data da Venda': '2023-04-28 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '31.88',
  'Quantidade em Estoque': '19',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-02-15 18:58:06.794203'},
 {'Nome do Item': 'Máscara de cílios',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '73.9',
  'Quantidade em Estoque': '83',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-07-02 18:58:06.794203'},
 {'Nome do Item': 'Batom líquido',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '48.62',
  'Quantidade em Estoque': '32',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-05-27 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '46.32',
  'Quantidade em Estoque': '52',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-04-12 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '6.9',
  'Quantidade em Estoque': '10',
  'Nome da Loja': 'Filial 4',
  'Data da Venda': '2023-03-23 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '26.51',
  'Quantidade em Estoque': '10',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2022-10-27 18:58:06.794203'},
 {'Nome do Item': 'Máscara de cílios',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '37.52',
  'Quantidade em Estoque': '55',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-02-13 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '18.37',
  'Quantidade em Estoque': '29',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-01-01 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '75.04',
  'Quantidade em Estoque': '90',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-08-29 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '9.59',
  'Quantidade em Estoque': '46',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-03-31 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '84.24',
  'Quantidade em Estoque': '27',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-03-07 18:58:06.794203'},
 {'Nome do Item': 'Base líquida',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '22.41',
  'Quantidade em Estoque': '97',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2022-09-11 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '18.03',
  'Quantidade em Estoque': '7',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2023-01-26 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '56.88',
  'Quantidade em Estoque': '49',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2023-02-01 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '71.07',
  'Quantidade em Estoque': '10',
  'Nome da Loja': 'Filial 4',
  'Data da Venda': '2023-01-01 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '80.43',
  'Quantidade em Estoque': '2',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2023-08-03 18:58:06.794203'},
 {'Nome do Item': 'Batom líquido',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '67.95',
  'Quantidade em Estoque': '50',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2022-10-06 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '15.85',
  'Quantidade em Estoque': '89',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-01-09 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '39.86',
  'Quantidade em Estoque': '31',
  'Nome da Loja': 'Filial 7',
  'Data da Venda': '2023-07-02 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '14.98',
  'Quantidade em Estoque': '40',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-06-04 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '6.9',
  'Quantidade em Estoque': '91',
  'Nome da Loja': 'Filial 9',
  'Data da Venda': '2023-02-23 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Roupas',
  'Valor em Reais (R$)': '57.28',
  'Quantidade em Estoque': '10',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-07-31 18:58:06.794203'},
 {'Nome do Item': 'Corretivo',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '11.71',
  'Quantidade em Estoque': '77',
  'Nome da Loja': 'Filial 6',
  'Data da Venda': '2022-11-18 18:58:06.794203'},
 {'Nome do Item': 'Blush em pó',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '60.0',
  'Quantidade em Estoque': '23',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2022-11-19 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '94.51',
  'Quantidade em Estoque': '72',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-01-14 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '86.96',
  'Quantidade em Estoque': '89',
  'Nome da Loja': 'Filial 7',
  'Data da Venda': '2022-11-25 18:58:06.794203'},
 {'Nome do Item': 'Máscara de cílios',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '36.37',
  'Quantidade em Estoque': '50',
  'Nome da Loja': 'Filial 1',
  'Data da Venda': '2022-09-29 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '9.36',
  'Quantidade em Estoque': '72',
  'Nome da Loja': 'Filial 5',
  'Data da Venda': '2023-07-21 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '43.3',
  'Quantidade em Estoque': '78',
  'Nome da Loja': 'Filial 6',
  'Data da Venda': '2023-02-11 18:58:06.794203'},
 {'Nome do Item': 'Batom matte',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '75.34',
  'Quantidade em Estoque': '75',
  'Nome da Loja': 'Filial 1',
  'Data da Venda': '2023-01-02 18:58:06.794203'},
 {'Nome do Item': 'Sombra de olhos',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '40.39',
  'Quantidade em Estoque': '84',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2022-12-16 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '11.05',
  'Quantidade em Estoque': '15',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2022-12-26 18:58:06.794203'},
 {'Nome do Item': 'Pó compacto',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '39.21',
  'Quantidade em Estoque': '26',
  'Nome da Loja': 'Filial 10',
  'Data da Venda': '2022-12-19 18:58:06.794203'},
 {'Nome do Item': 'Delineador líquido',
  'Classificação do Produto': 'Alimentos',
  'Valor em Reais (R$)': '48.01',
  'Quantidade em Estoque': '46',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2023-02-14 18:58:06.794203'},
 {'Nome do Item': 'Máscara de cílios',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '1.65',
  'Quantidade em Estoque': '79',
  'Nome da Loja': 'Filial 8',
  'Data da Venda': '2022-10-21 18:58:06.794203'},
 {'Nome do Item': 'Máscara de cílios',
  'Classificação do Produto': 'Eletrodomésticos',
  'Valor em Reais (R$)': '43.61',
  'Quantidade em Estoque': '75',
  'Nome da Loja': 'Filial 2',
  'Data da Venda': '2022-09-26 18:58:06.794203'},
 {'Nome do Item': 'Lápis de sobrancelha',
  'Classificação do Produto': 'Eletrônicos',
  'Valor em Reais (R$)': '75.25',
  'Quantidade em Estoque': '11',
  'Nome da Loja': 'Filial 3',
  'Data da Venda': '2023-08-04 18:58:06.794203'},

### Utilizando Pandas

In [20]:
import pandas as pd

df_json =  pd.read_json(path_json)
df_csv =  pd.read_csv(path_csv)

df_csv

,Nome do Item,Classificação do Produto,Valor em Reais (R$),Quantidade em Estoque,Nome da Loja,Data da Venda
0,Lápis de sobrancelha,Roupas,55.17,62,Filial 1,2023-04-13 18:58:06.794203
1,Batom matte,Eletrônicos,74.15,48,Filial 9,2023-06-03 18:58:06.794203
2,Corretivo,Roupas,54.86,36,Filial 5,2023-06-08 18:58:06.794203
3,Delineador líquido,Roupas,91.29,1,Filial 8,2023-02-27 18:58:06.794203
4,Batom líquido,Roupas,44.65,52,Filial 2,2022-09-05 18:58:06.794203
...,...,...,...,...,...,...
1318,Lápis de sobrancelha,Alimentos,94.08,94,Filial 7,2022-11-20 18:58:06.794203
1319,Corretivo,Roupas,5.60,49,Filial 4,2023-07-16 18:58:06.794203
1320,Pó compacto,Eletrônicos,22.36,16,Filial 3,2023-01-24 18:58:06.794203
1321,Base líquida,Roupas,3.79,5,Filial 5,2022-12-18 18:58:06.794203
1322,Sombra de olhos,Eletrônicos,41.73,5,Filial 6,2022-11-21 18:58:06.794203

In [21]:
df_json

,Nome do Produto,Categoria do Produto,Preço do Produto (R$),Quantidade em Estoque,Filial
0,Blush em pó,Eletrodomésticos,79.41,7,Filial 7
1,Lápis de sobrancelha,Eletrodomésticos,85.47,78,Filial 8
2,Base líquida,Roupas,75.02,34,Filial 8
3,Base líquida,Roupas,44.94,90,Filial 10
4,Lápis de sobrancelha,Alimentos,58.63,91,Filial 7
...,...,...,...,...,...
3118,Lápis de sobrancelha,Alimentos,91.77,5,Filial 2
3119,Pó compacto,Eletrodomésticos,43.46,43,Filial 3
3120,Lápis de sobrancelha,Roupas,63.69,7,Filial 3
3121,Lápis de sobrancelha,Eletrônicos,72.83,55,Filial 3
3122,Delineador líquido,Eletrônicos,64.68,48,Filial 8

### Explorando os dados e arrumando as diferenças

In [26]:
colunas_nomes_json = list(dados_json[0].keys())
colunas_nomes_json

['Nome do Produto',
 'Categoria do Produto',
 'Preço do Produto (R$)',
 'Quantidade em Estoque',
 'Filial']

In [27]:
colunas_nomes_csv = list(dados_csv[0].keys())
colunas_nomes_csv

['Nome do Item',
 'Classificação do Produto',
 'Valor em Reais (R$)',
 'Quantidade em Estoque',
 'Nome da Loja',
 'Data da Venda']

In [39]:
key_map = {
    'Nome do Item' : 'Nome do Produto',
    'Classificação do Produto': 'Categoria do Produto',
    'Valor em Reais (R$)':  'Preço do Produto (R$)',
    'Quantidade em Estoque': 'Quantidade em Estoque',
    'Nome da Loja' : 'Filial', 
    'Data da Venda': 'Data da Venda'
}

In [ ]:
new_dados_csv = []
for old_dict in dados_csv:
    dict_temp = {} #Dicionario temporario
    print(dict_temp)
    for old_key, value in old_dict.items():
        print(old_key) #Nome do Item
        print(value) #valor Item
        print(key_map[old_key]) #Nome do Produto
        #Dicionario não precisa do "append", apenas dicionario[nome da coluna] = valor            
        dict_temp[key_map[old_key]] = value
        print(dict_temp[key_map[old_key]])
        print(dict_temp)
    new_dados_csv.append(dict_temp)
new_dados_csv[0]

{}
Nome do Item
Lápis de sobrancelha
Nome do Produto
Lápis de sobrancelha
{'Nome do Produto': 'Lápis de sobrancelha'}
Classificação do Produto
Roupas
Categoria do Produto
Roupas
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Roupas'}
Valor em Reais (R$)
55.17
Preço do Produto (R$)
55.17
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '55.17'}
Quantidade em Estoque
62
Quantidade em Estoque
62
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '55.17', 'Quantidade em Estoque': '62'}
Nome da Loja
Filial 1
Filial
Filial 1
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '55.17', 'Quantidade em Estoque': '62', 'Filial': 'Filial 1'}
Data da Venda
2023-04-13 18:58:06.794203
Data da Venda
2023-04-13 18:58:06.794203
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '55.17', 'Quantidade em Estoque': '62', 'Filial': 'Filial 1', 'Data da Venda': '2023-04-13 18:58:06.794203'}
{}
Nome do Item
Batom matte
Nome do Produto
Batom matte
{'Nome do Produto': 'Batom matte'}
Classificação do Produto
Eletrônicos
Categoria do Produto
Eletrônicos
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Eletrônicos'}
Valor em Reais (R$)
74.15
Preço do Produto (R$)
74.15
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '74.15'}
Quantidade em Estoque
48
Quantidade em Estoque
48
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '74.15', 'Quantidade em Estoque': '48'}
Nome da Loja
Filial 9
Filial
Filial 9
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '74.15', 'Quantidade em Estoque': '48', 'Filial': 'Filial 9'}
Data da Venda
2023-06-03 18:58:06.794203
Data da Venda
2023-06-03 18:58:06.794203
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '74.15', 'Quantidade em Estoque': '48', 'Filial': 'Filial 9', 'Data da Venda': '2023-06-03 18:58:06.794203'}
{}
Nome do Item
Corretivo
Nome do Produto
Corretivo
{'Nome do Produto': 'Corretivo'}
Classificação do Produto
Roupas
Categoria do Produto
Roupas
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas'}
Valor em Reais (R$)
54.86
Preço do Produto (R$)
54.86
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '54.86'}
Quantidade em Estoque
36
Quantidade em Estoque
36
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '54.86', 'Quantidade em Estoque': '36'}
Nome da Loja
Filial 5
Filial
Filial 5
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '54.86', 'Quantidade em Estoque': '36', 'Filial': 'Filial 5'}
Data da Venda
2023-06-08 18:58:06.794203
Data da Venda
2023-06-08 18:58:06.794203
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '54.86', 'Quantidade em Estoque': '36', 'Filial': 'Filial 5', 'Data da Venda': '2023-06-08 18:58:06.794203'}
{}
Nome do Item
Delineador líquido
Nome do Produto
Delineador líquido
{'Nome do Produto': 'Delineador líquido'}
Classificação do Produto
Roupas
Categoria do Produto
Roupas
{'Nome do Produto': 'Delineador líquido', 'Categoria do Produto': 'Roupas'}
Valor em Reais (R$)
91.29
Preço do Produto (R$)
91.29
{'Nome do Produto': 'Delineador líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '91.29'}
Quantidade em Estoque
1
Quantidade em Estoque
1
{'Nome do Produto': 'Delineador líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '91.29', 'Quantidade em Estoque': '1'}
Nome da Loja
Filial 8
Filial
Filial 8
{'Nome do Produto': 'Delineador líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '91.29', 'Quantidade em Estoque': '1', 'Filial': 'Filial 8'}
Data da Venda
2023-02-27 18:58:06.794203
Data da Venda
2023-02-27 18:58:06.794203
{'Nome do Produto': 'Delineador líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '91.29', 'Quantidade em Estoque': '1', 'Filial': 'Filial 8', 'Data da Venda': '2023-02-27 18:58:06.794203'}
{}
Nome do Item
Batom líquido
Nome do Produto
Batom líquido
{'Nome do Produto': 'Batom líquido'}
Classificação do Produto
Roupas
Categoria do Produto
Roupas
{'Nome do Produto': 'Batom líquido', 'Categoria do Produto': 'Roupas'}
Valor em Reais (R$)
44.65
Preço do Produto (R$)
44.65
{'Nome do Produto': 'Batom líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '44.65'}
Quantidade em Estoque
52
Quantidade em Estoque
52
{'Nome do Produto': 'Batom líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '44.65', 'Quantidade em Estoque': '52'}
Nome da Loja
Filial 2
Filial
Filial 2
{'Nome do Produto': 'Batom líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '44.65', 'Quantidade em Estoque': '52', 'Filial': 'Filial 2'}
Data da Venda
2022-09-05 18:58:06.794203
Data da Venda
2022-09-05 18:58:06.794203
{'Nome do Produto': 'Batom líquido', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '44.65', 'Quantidade em Estoque': '52', 'Filial': 'Filial 2', 'Data da Venda': '2022-09-05 18:58:06.794203'}
{}
Nome do Item
Base líquida
Nome do Produto
Base líquida
{'Nome do Produto': 'Base líquida'}
Classificação do Produto
Eletrônicos
Categoria do Produto
Eletrônicos
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Eletrônicos'}
Valor em Reais (R$)
5.22
Preço do Produto (R$)
5.22
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.22'}
Quantidade em Estoque
85
Quantidade em Estoque
85
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.22', 'Quantidade em Estoque': '85'}
Nome da Loja
Filial 3
Filial
Filial 3
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.22', 'Quantidade em Estoque': '85', 'Filial': 'Filial 3'}
Data da Venda
2022-09-11 18:58:06.794203
Data da Venda
2022-09-11 18:58:06.794203
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.22', 'Quantidade em Estoque': '85', 'Filial': 'Filial 3', 'Data da Venda': '2022-09-11 18:58:06.794203'}
{}
Nome do Item
Máscara de cílios
Nome do Produto
Máscara de cílios
{'Nome do Produto': 'Máscara de cílios'}
Classificação do Produto
Eletrônicos
Categoria do Produto
Eletrônicos
{'Nome do Produto': 'Máscara de cílios', 'Categoria do Produto': 'Eletrônicos'}
Valor em Reais (R$)
1.08
Preço do Produto (R$)
1.08
{'Nome do Produto': 'Máscara de cílios', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '1.08'}
Quantidade em Estoque
31
Quantidade em Estoque
31
{'Nome do Produto': 'Máscara de cílios', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '1.08', 'Quantidade em Estoque': '31'}
Nome da Loja
Filial 6
Filial
Filial 6
{'Nome do Produto': 'Máscara de cílios', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '1.08', 'Quantidade em Estoque': '31', 'Filial': 'Filial 6'}
Data da Venda
2023-02-08 18:58:06.794203
Data da Venda
2023-02-08 18:58:06.794203
{'Nome do Produto': 'Máscara de cílios', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '1.08', 'Quantidade em Estoque': '31', 'Filial': 'Filial 6', 'Data da Venda': '2023-02-08 18:58:06.794203'}
{}
Nome do Item
Corretivo
Nome do Produto
Corretivo
{'Nome do Produto': 'Corretivo'}
Classificação do Produto
Alimentos
Categoria do Produto
Alimentos
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Alimentos'}
Valor em Reais (R$)
56.22
Preço do Produto (R$)
56.22
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '56.22'}
Quantidade em Estoque
76
Quantidade em Estoque
76
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '56.22', 'Quantidade em Estoque': '76'}
Nome da Loja
Filial 5
Filial
Filial 5
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '56.22', 'Quantidade em Estoque': '76', 'Filial': 'Filial 5'}
Data da Venda
2022-12-08 18:58:06.794203
Data da Venda
2022-12-08 18:58:06.794203
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '56.22', 'Quantidade em Estoque': '76', 'Filial': 'Filial 5', 'Data da Venda': '2022-12-08 18:58:06.794203'}
{}
Nome do Item
Batom matte
Nome do Produto
Batom matte
{'Nome do Produto': 'Batom matte'}
Classificação do Produto
Roupas
Categoria do Produto
Roupas
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Roupas'}
Valor em Reais (R$)
94.01
Preço do Produto (R$)
94.01
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '94.01'}
Quantidade em Estoque
7
Quantidade em Estoque
7
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '94.01', 'Quantidade em Estoque': '7'}
Nome da Loja
Filial 2
Filial
Filial 2
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '94.01', 'Quantidade em Estoque': '7', 'Filial': 'Filial 2'}
Data da Venda
2023-07-18 18:58:06.794203
Data da Venda
2023-07-18 18:58:06.794203
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '94.01', 'Quantidade em Estoque': '7', 'Filial': 'Filial 2', 'Data da Venda': '2023-07-18 18:58:06.794203'}
{}
Nome do Item
Lápis de sobrancelha
Nome do Produto
Lápis de sobrancelha
{'Nome do Produto': 'Lápis de sobrancelha'}
Classificação do Produto
Alimentos
Categoria do Produto
Alimentos
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Alimentos'}
Valor em Reais (R$)
51.38
Preço do Produto (R$)
51.38
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.38'}
Quantidade em Estoque
4
Quantidade em Estoque
4
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.38', 'Quantidade em Estoque': '4'}
Nome da Loja
Filial 10
Filial
Filial 10
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.38', 'Quantidade em Estoque': '4', 'Filial': 'Filial 10'}
Data da Venda
2023-06-19 18:58:06.794203
Data da Venda
2023-06-19 18:58:06.794203
{'Nome do Produto': 'Lápis de sobrancelha', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.38', 'Quantidade em Estoque': '4', 'Filial': 'Filial 10', 'Data da Venda': '2023-06-19 18:58:06.794203'}
{}
Nome do Item
Pó compacto
Nome do Produto
Pó compacto
{'Nome do Produto': 'Pó compacto'}
Classificação do Produto
Eletrônicos
Categoria do Produto
Eletrônicos
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos'}
Valor em Reais (R$)
5.59
Preço do Produto (R$)
5.59
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.59'}
Quantidade em Estoque
82
Quantidade em Estoque
82
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.59', 'Quantidade em Estoque': '82'}
Nome da Loja
Filial 10
Filial
Filial 10
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.59', 'Quantidade em Estoque': '82', 'Filial': 'Filial 10'}
Data da Venda
2023-07-19 18:58:06.794203
Data da Venda
2023-07-19 18:58:06.794203
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '5.59', 'Quantidade em Estoque': '82', 'Filial': 'Filial 10', 'Data da Venda': '2023-07-19 18:58:06.794203'}
{}
Nome do Item
Pó compacto
Nome do Produto
Pó compacto
{'Nome do Produto': 'Pó compacto'}
Classificação do Produto
Eletrônicos
Categoria do Produto
Eletrônicos
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos'}
Valor em Reais (R$)
2.65
Preço do Produto (R$)
2.65
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '2.65'}
Quantidade em Estoque
8
Quantidade em Estoque
8
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '2.65', 'Quantidade em Estoque': '8'}
Nome da Loja
Filial 3
Filial
Filial 3
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '2.65', 'Quantidade em Estoque': '8', 'Filial': 'Filial 3'}
Data da Venda
2023-05-24 18:58:06.794203
Data da Venda
2023-05-24 18:58:06.794203
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Eletrônicos', 'Preço do Produto (R$)': '2.65', 'Quantidade em Estoque': '8', 'Filial': 'Filial 3', 'Data da Venda': '2023-05-24 18:58:06.794203'}
{}
Nome do Item
Corretivo
Nome do Produto
Corretivo
{'Nome do Produto': 'Corretivo'}
Classificação do Produto
Roupas
Categoria do Produto
Roupas
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas'}
Valor em Reais (R$)
68.62
Preço do Produto (R$)
68.62
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '68.62'}
Quantidade em Estoque
6
Quantidade em Estoque
6
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '68.62', 'Quantidade em Estoque': '6'}
Nome da Loja
Filial 1
Filial
Filial 1
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '68.62', 'Quantidade em Estoque': '6', 'Filial': 'Filial 1'}
Data da Venda
2023-01-24 18:58:06.794203
Data da Venda
2023-01-24 18:58:06.794203
{'Nome do Produto': 'Corretivo', 'Categoria do Produto': 'Roupas', 'Preço do Produto (R$)': '68.62', 'Quantidade em Estoque': '6', 'Filial': 'Filial 1', 'Data da Venda': '2023-01-24 18:58:06.794203'}
{}
Nome do Item
Pó compacto
Nome do Produto
Pó compacto
{'Nome do Produto': 'Pó compacto'}
Classificação do Produto
Alimentos
Categoria do Produto
Alimentos
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Alimentos'}
Valor em Reais (R$)
80.94
Preço do Produto (R$)
80.94
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '80.94'}
Quantidade em Estoque
70
Quantidade em Estoque
70
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '80.94', 'Quantidade em Estoque': '70'}
Nome da Loja
Filial 6
Filial
Filial 6
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '80.94', 'Quantidade em Estoque': '70', 'Filial': 'Filial 6'}
Data da Venda
2023-06-07 18:58:06.794203
Data da Venda
2023-06-07 18:58:06.794203
{'Nome do Produto': 'Pó compacto', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '80.94', 'Quantidade em Estoque': '70', 'Filial': 'Filial 6', 'Data da Venda': '2023-06-07 18:58:06.794203'}
{}
Nome do Item
Batom matte
Nome do Produto
Batom matte
{'Nome do Produto': 'Batom matte'}
Classificação do Produto
Alimentos
Categoria do Produto
Alimentos
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Alimentos'}
Valor em Reais (R$)
26.79
Preço do Produto (R$)
26.79
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '26.79'}
Quantidade em Estoque
86
Quantidade em Estoque
86
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '26.79', 'Quantidade em Estoque': '86'}
Nome da Loja
Filial 9
Filial
Filial 9
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '26.79', 'Quantidade em Estoque': '86', 'Filial': 'Filial 9'}
Data da Venda
2023-01-10 18:58:06.794203
Data da Venda
2023-01-10 18:58:06.794203
{'Nome do Produto': 'Batom matte', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '26.79', 'Quantidade em Estoque': '86', 'Filial': 'Filial 9', 'Data da Venda': '2023-01-10 18:58:06.794203'}
{}
Nome do Item
Base líquida
Nome do Produto
Base líquida
{'Nome do Produto': 'Base líquida'}
Classificação do Produto
Alimentos
Categoria do Produto
Alimentos
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos'}
Valor em Reais (R$)
55.08
Preço do Produto (R$)
55.08
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '55.08'}
Quantidade em Estoque
14
Quantidade em Estoque
14
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '55.08', 'Quantidade em Estoque': '14'}
Nome da Loja
Filial 5
Filial
Filial 5
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '55.08', 'Quantidade em Estoque': '14', 'Filial': 'Filial 5'}
Data da Venda
2023-02-09 18:58:06.794203
Data da Venda
2023-02-09 18:58:06.794203
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '55.08', 'Quantidade em Estoque': '14', 'Filial': 'Filial 5', 'Data da Venda': '2023-02-09 18:58:06.794203'}
{}
Nome do Item
Base líquida
Nome do Produto
Base líquida
{'Nome do Produto': 'Base líquida'}
Classificação do Produto
Alimentos
Categoria do Produto
Alimentos
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos'}
Valor em Reais (R$)
51.34
Preço do Produto (R$)
51.34
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.34'}
Quantidade em Estoque
13
Quantidade em Estoque
13
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.34', 'Quantidade em Estoque': '13'}
Nome da Loja
Filial 2
Filial
Filial 2
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.34', 'Quantidade em Estoque': '13', 'Filial': 'Filial 2'}
Data da Venda
2022-10-24 18:58:06.794203
Data da Venda
2022-10-24 18:58:06.794203
{'Nome do Produto': 'Base líquida', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '51.34', 'Quantidade em Estoque': '13', 'Filial': 'Filial 2', 'Data da Venda': '2022-10-24 18:58:06.794203'}
{}
Nome do Item
Sombra de olhos
Nome do Produto
Sombra de olhos
{'Nome do Produto': 'Sombra de olhos'}
Classificação do Produto
Alimentos
Categoria do Produto
Alimentos
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Alimentos'}
Valor em Reais (R$)
31.07
Preço do Produto (R$)
31.07
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '31.07'}
Quantidade em Estoque
45
Quantidade em Estoque
45
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '31.07', 'Quantidade em Estoque': '45'}
Nome da Loja
Filial 8
Filial
Filial 8
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '31.07', 'Quantidade em Estoque': '45', 'Filial': 'Filial 8'}
Data da Venda
2023-03-06 18:58:06.794203
Data da Venda
2023-03-06 18:58:06.794203
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Alimentos', 'Preço do Produto (R$)': '31.07', 'Quantidade em Estoque': '45', 'Filial': 'Filial 8', 'Data da Venda': '2023-03-06 18:58:06.794203'}
{}
Nome do Item
Sombra de olhos
Nome do Produto
Sombra de olhos
{'Nome do Produto': 'Sombra de olhos'}
Classificação do Produto
Eletrodomésticos
Categoria do Produto
Eletrodomésticos
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Eletrodomésticos'}
Valor em Reais (R$)
78.94
Preço do Produto (R$)
78.94
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Eletrodomésticos', 'Preço do Produto (R$)': '78.94'}
Quantidade em Estoque
44
Quantidade em Estoque
44
{'Nome do Produto': 'Sombra de olhos', 'Categoria do Produto': 'Eletrodomésticos', 'Preço do Produto (R$)': '78.94', 'Quantidade em Estoque': '44'}
Nome da Loja
Filial 7
Filial
Filial 7

{'Nome do Produto': 'Lápis de sobrancelha',
 'Categoria do Produto': 'Roupas',
 'Preço do Produto (R$)': '55.17',
 'Quantidade em Estoque': '62',
 'Filial': 'Filial 1',
 'Data da Venda': '2023-04-13 18:58:06.794203'}

In [48]:
#list comprehension
novos_dados_csv = [{key_map.get(old_key): value for old_key, value in old_dict.items()} for old_dict in dados_csv]

novos_dados_csv

[{'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '55.17',
  'Quantidade em Estoque': '62',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-04-13 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '74.15',
  'Quantidade em Estoque': '48',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-06-03 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '54.86',
  'Quantidade em Estoque': '36',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-06-08 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '91.29',
  'Quantidade em Estoque': '1',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-02-27 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '44.65',
  'Quantidade em Estoque': '52',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-09-05 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '5.22',
  'Quantidade em Estoque': '85',
  'Filial': 'Filial 3',
  'Data da Venda': '2022-09-11 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '1.08',
  'Quantidade em Estoque': '31',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-02-08 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '56.22',
  'Quantidade em Estoque': '76',
  'Filial': 'Filial 5',
  'Data da Venda': '2022-12-08 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '94.01',
  'Quantidade em Estoque': '7',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-07-18 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '51.38',
  'Quantidade em Estoque': '4',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-06-19 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '5.59',
  'Quantidade em Estoque': '82',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-07-19 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '2.65',
  'Quantidade em Estoque': '8',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-05-24 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '68.62',
  'Quantidade em Estoque': '6',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-01-24 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '80.94',
  'Quantidade em Estoque': '70',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-06-07 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '26.79',
  'Quantidade em Estoque': '86',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-01-10 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '55.08',
  'Quantidade em Estoque': '14',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-02-09 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '51.34',
  'Quantidade em Estoque': '13',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-10-24 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '31.07',
  'Quantidade em Estoque': '45',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-03-06 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '78.94',
  'Quantidade em Estoque': '44',
  'Filial': 'Filial 7',
  'Data da Venda': '2022-11-12 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '41.15',
  'Quantidade em Estoque': '91',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-02-03 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '44.47',
  'Quantidade em Estoque': '39',
  'Filial': 'Filial 4',
  'Data da Venda': '2023-07-31 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '32.8',
  'Quantidade em Estoque': '23',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-06-07 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '90.62',
  'Quantidade em Estoque': '70',
  'Filial': 'Filial 3',
  'Data da Venda': '2022-10-31 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '66.56',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-03-04 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '57.56',
  'Quantidade em Estoque': '77',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-01-27 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '40.92',
  'Quantidade em Estoque': '13',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-04-25 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '65.96',
  'Quantidade em Estoque': '73',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-09-20 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '87.64',
  'Quantidade em Estoque': '25',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-03-09 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '61.21',
  'Quantidade em Estoque': '22',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-02-06 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '12.77',
  'Quantidade em Estoque': '57',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-05-15 18:58:06.794203'},
 {'Nome do Produto': 'Blush em pó',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '86.67',
  'Quantidade em Estoque': '61',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-07-06 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '26.87',
  'Quantidade em Estoque': '56',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-07-24 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '83.86',
  'Quantidade em Estoque': '33',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-05-02 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '89.13',
  'Quantidade em Estoque': '49',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-07-07 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '12.08',
  'Quantidade em Estoque': '87',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-04-15 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '73.5',
  'Quantidade em Estoque': '67',
  'Filial': 'Filial 4',
  'Data da Venda': '2022-11-07 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '90.34',
  'Quantidade em Estoque': '76',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-06-16 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '5.74',
  'Quantidade em Estoque': '1',
  'Filial': 'Filial 4',
  'Data da Venda': '2022-12-15 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '47.47',
  'Quantidade em Estoque': '62',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-02-01 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '87.52',
  'Quantidade em Estoque': '43',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-08-22 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '14.57',
  'Quantidade em Estoque': '72',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-05-20 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '69.69',
  'Quantidade em Estoque': '9',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-02-03 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '62.96',
  'Quantidade em Estoque': '12',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-05-02 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '52.49',
  'Quantidade em Estoque': '57',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-03-10 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '85.51',
  'Quantidade em Estoque': '5',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-04-17 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '8.72',
  'Quantidade em Estoque': '48',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-05-16 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '78.58',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-12-16 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '23.8',
  'Quantidade em Estoque': '28',
  'Filial': 'Filial 9',
  'Data da Venda': '2022-10-14 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '36.96',
  'Quantidade em Estoque': '5',
  'Filial': 'Filial 3',
  'Data da Venda': '2022-11-05 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '13.84',
  'Quantidade em Estoque': '2',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-04-30 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '23.45',
  'Quantidade em Estoque': '69',
  'Filial': 'Filial 7',
  'Data da Venda': '2023-04-28 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '31.88',
  'Quantidade em Estoque': '19',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-02-15 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '73.9',
  'Quantidade em Estoque': '83',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-07-02 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '48.62',
  'Quantidade em Estoque': '32',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-05-27 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '46.32',
  'Quantidade em Estoque': '52',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-04-12 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '6.9',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 4',
  'Data da Venda': '2023-03-23 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '26.51',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-10-27 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '37.52',
  'Quantidade em Estoque': '55',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-02-13 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '18.37',
  'Quantidade em Estoque': '29',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-01-01 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '75.04',
  'Quantidade em Estoque': '90',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-08-29 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '9.59',
  'Quantidade em Estoque': '46',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-03-31 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '84.24',
  'Quantidade em Estoque': '27',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-03-07 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '22.41',
  'Quantidade em Estoque': '97',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-09-11 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '18.03',
  'Quantidade em Estoque': '7',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-01-26 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '56.88',
  'Quantidade em Estoque': '49',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-02-01 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '71.07',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 4',
  'Data da Venda': '2023-01-01 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '80.43',
  'Quantidade em Estoque': '2',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-08-03 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '67.95',
  'Quantidade em Estoque': '50',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-10-06 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '15.85',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-01-09 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '39.86',
  'Quantidade em Estoque': '31',
  'Filial': 'Filial 7',
  'Data da Venda': '2023-07-02 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '14.98',
  'Quantidade em Estoque': '40',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-06-04 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '6.9',
  'Quantidade em Estoque': '91',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-02-23 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '57.28',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-07-31 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '11.71',
  'Quantidade em Estoque': '77',
  'Filial': 'Filial 6',
  'Data da Venda': '2022-11-18 18:58:06.794203'},
 {'Nome do Produto': 'Blush em pó',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '60.0',
  'Quantidade em Estoque': '23',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-11-19 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '94.51',
  'Quantidade em Estoque': '72',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-01-14 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '86.96',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 7',
  'Data da Venda': '2022-11-25 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '36.37',
  'Quantidade em Estoque': '50',
  'Filial': 'Filial 1',
  'Data da Venda': '2022-09-29 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '9.36',
  'Quantidade em Estoque': '72',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-07-21 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '43.3',
  'Quantidade em Estoque': '78',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-02-11 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '75.34',
  'Quantidade em Estoque': '75',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-01-02 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '40.39',
  'Quantidade em Estoque': '84',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-12-16 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '11.05',
  'Quantidade em Estoque': '15',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-12-26 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '39.21',
  'Quantidade em Estoque': '26',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-12-19 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '48.01',
  'Quantidade em Estoque': '46',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-02-14 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '1.65',
  'Quantidade em Estoque': '79',
  'Filial': 'Filial 8',
  'Data da Venda': '2022-10-21 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '43.61',
  'Quantidade em Estoque': '75',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-09-26 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '75.25',
  'Quantidade em Estoque': '11',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-08-04 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '55.73',
  'Quantidade em Estoque': '25',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-06-06 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '11.96',
  'Quantidade em Estoque': '7',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-03-25 18:58:06.794203'},

In [88]:
combined_list = []
combined_list.extend(new_dados_csv)
combined_list.extend(dados_json)




len(combined_list)

4446

In [89]:
combined_list

[{'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '55.17',
  'Quantidade em Estoque': '62',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-04-13 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '74.15',
  'Quantidade em Estoque': '48',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-06-03 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '54.86',
  'Quantidade em Estoque': '36',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-06-08 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '91.29',
  'Quantidade em Estoque': '1',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-02-27 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '44.65',
  'Quantidade em Estoque': '52',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-09-05 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '5.22',
  'Quantidade em Estoque': '85',
  'Filial': 'Filial 3',
  'Data da Venda': '2022-09-11 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '1.08',
  'Quantidade em Estoque': '31',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-02-08 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '56.22',
  'Quantidade em Estoque': '76',
  'Filial': 'Filial 5',
  'Data da Venda': '2022-12-08 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '94.01',
  'Quantidade em Estoque': '7',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-07-18 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '51.38',
  'Quantidade em Estoque': '4',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-06-19 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '5.59',
  'Quantidade em Estoque': '82',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-07-19 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '2.65',
  'Quantidade em Estoque': '8',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-05-24 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '68.62',
  'Quantidade em Estoque': '6',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-01-24 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '80.94',
  'Quantidade em Estoque': '70',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-06-07 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '26.79',
  'Quantidade em Estoque': '86',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-01-10 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '55.08',
  'Quantidade em Estoque': '14',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-02-09 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '51.34',
  'Quantidade em Estoque': '13',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-10-24 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '31.07',
  'Quantidade em Estoque': '45',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-03-06 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '78.94',
  'Quantidade em Estoque': '44',
  'Filial': 'Filial 7',
  'Data da Venda': '2022-11-12 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '41.15',
  'Quantidade em Estoque': '91',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-02-03 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '44.47',
  'Quantidade em Estoque': '39',
  'Filial': 'Filial 4',
  'Data da Venda': '2023-07-31 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '32.8',
  'Quantidade em Estoque': '23',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-06-07 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '90.62',
  'Quantidade em Estoque': '70',
  'Filial': 'Filial 3',
  'Data da Venda': '2022-10-31 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '66.56',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-03-04 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '57.56',
  'Quantidade em Estoque': '77',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-01-27 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '40.92',
  'Quantidade em Estoque': '13',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-04-25 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '65.96',
  'Quantidade em Estoque': '73',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-09-20 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '87.64',
  'Quantidade em Estoque': '25',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-03-09 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '61.21',
  'Quantidade em Estoque': '22',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-02-06 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '12.77',
  'Quantidade em Estoque': '57',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-05-15 18:58:06.794203'},
 {'Nome do Produto': 'Blush em pó',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '86.67',
  'Quantidade em Estoque': '61',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-07-06 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '26.87',
  'Quantidade em Estoque': '56',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-07-24 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '83.86',
  'Quantidade em Estoque': '33',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-05-02 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '89.13',
  'Quantidade em Estoque': '49',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-07-07 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '12.08',
  'Quantidade em Estoque': '87',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-04-15 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '73.5',
  'Quantidade em Estoque': '67',
  'Filial': 'Filial 4',
  'Data da Venda': '2022-11-07 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '90.34',
  'Quantidade em Estoque': '76',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-06-16 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '5.74',
  'Quantidade em Estoque': '1',
  'Filial': 'Filial 4',
  'Data da Venda': '2022-12-15 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '47.47',
  'Quantidade em Estoque': '62',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-02-01 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '87.52',
  'Quantidade em Estoque': '43',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-08-22 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '14.57',
  'Quantidade em Estoque': '72',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-05-20 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '69.69',
  'Quantidade em Estoque': '9',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-02-03 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '62.96',
  'Quantidade em Estoque': '12',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-05-02 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '52.49',
  'Quantidade em Estoque': '57',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-03-10 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '85.51',
  'Quantidade em Estoque': '5',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-04-17 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '8.72',
  'Quantidade em Estoque': '48',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-05-16 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '78.58',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-12-16 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '23.8',
  'Quantidade em Estoque': '28',
  'Filial': 'Filial 9',
  'Data da Venda': '2022-10-14 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '36.96',
  'Quantidade em Estoque': '5',
  'Filial': 'Filial 3',
  'Data da Venda': '2022-11-05 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '13.84',
  'Quantidade em Estoque': '2',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-04-30 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '23.45',
  'Quantidade em Estoque': '69',
  'Filial': 'Filial 7',
  'Data da Venda': '2023-04-28 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '31.88',
  'Quantidade em Estoque': '19',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-02-15 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '73.9',
  'Quantidade em Estoque': '83',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-07-02 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '48.62',
  'Quantidade em Estoque': '32',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-05-27 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '46.32',
  'Quantidade em Estoque': '52',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-04-12 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '6.9',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 4',
  'Data da Venda': '2023-03-23 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '26.51',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-10-27 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '37.52',
  'Quantidade em Estoque': '55',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-02-13 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '18.37',
  'Quantidade em Estoque': '29',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-01-01 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '75.04',
  'Quantidade em Estoque': '90',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-08-29 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '9.59',
  'Quantidade em Estoque': '46',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-03-31 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '84.24',
  'Quantidade em Estoque': '27',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-03-07 18:58:06.794203'},
 {'Nome do Produto': 'Base líquida',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '22.41',
  'Quantidade em Estoque': '97',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-09-11 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '18.03',
  'Quantidade em Estoque': '7',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-01-26 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '56.88',
  'Quantidade em Estoque': '49',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-02-01 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '71.07',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 4',
  'Data da Venda': '2023-01-01 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '80.43',
  'Quantidade em Estoque': '2',
  'Filial': 'Filial 10',
  'Data da Venda': '2023-08-03 18:58:06.794203'},
 {'Nome do Produto': 'Batom líquido',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '67.95',
  'Quantidade em Estoque': '50',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-10-06 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '15.85',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-01-09 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '39.86',
  'Quantidade em Estoque': '31',
  'Filial': 'Filial 7',
  'Data da Venda': '2023-07-02 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '14.98',
  'Quantidade em Estoque': '40',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-06-04 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '6.9',
  'Quantidade em Estoque': '91',
  'Filial': 'Filial 9',
  'Data da Venda': '2023-02-23 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '57.28',
  'Quantidade em Estoque': '10',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-07-31 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '11.71',
  'Quantidade em Estoque': '77',
  'Filial': 'Filial 6',
  'Data da Venda': '2022-11-18 18:58:06.794203'},
 {'Nome do Produto': 'Blush em pó',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '60.0',
  'Quantidade em Estoque': '23',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-11-19 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '94.51',
  'Quantidade em Estoque': '72',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-01-14 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '86.96',
  'Quantidade em Estoque': '89',
  'Filial': 'Filial 7',
  'Data da Venda': '2022-11-25 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '36.37',
  'Quantidade em Estoque': '50',
  'Filial': 'Filial 1',
  'Data da Venda': '2022-09-29 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '9.36',
  'Quantidade em Estoque': '72',
  'Filial': 'Filial 5',
  'Data da Venda': '2023-07-21 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '43.3',
  'Quantidade em Estoque': '78',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-02-11 18:58:06.794203'},
 {'Nome do Produto': 'Batom matte',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '75.34',
  'Quantidade em Estoque': '75',
  'Filial': 'Filial 1',
  'Data da Venda': '2023-01-02 18:58:06.794203'},
 {'Nome do Produto': 'Sombra de olhos',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '40.39',
  'Quantidade em Estoque': '84',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-12-16 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '11.05',
  'Quantidade em Estoque': '15',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-12-26 18:58:06.794203'},
 {'Nome do Produto': 'Pó compacto',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '39.21',
  'Quantidade em Estoque': '26',
  'Filial': 'Filial 10',
  'Data da Venda': '2022-12-19 18:58:06.794203'},
 {'Nome do Produto': 'Delineador líquido',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '48.01',
  'Quantidade em Estoque': '46',
  'Filial': 'Filial 8',
  'Data da Venda': '2023-02-14 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '1.65',
  'Quantidade em Estoque': '79',
  'Filial': 'Filial 8',
  'Data da Venda': '2022-10-21 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Eletrodomésticos',
  'Preço do Produto (R$)': '43.61',
  'Quantidade em Estoque': '75',
  'Filial': 'Filial 2',
  'Data da Venda': '2022-09-26 18:58:06.794203'},
 {'Nome do Produto': 'Lápis de sobrancelha',
  'Categoria do Produto': 'Eletrônicos',
  'Preço do Produto (R$)': '75.25',
  'Quantidade em Estoque': '11',
  'Filial': 'Filial 3',
  'Data da Venda': '2023-08-04 18:58:06.794203'},
 {'Nome do Produto': 'Máscara de cílios',
  'Categoria do Produto': 'Alimentos',
  'Preço do Produto (R$)': '55.73',
  'Quantidade em Estoque': '25',
  'Filial': 'Filial 2',
  'Data da Venda': '2023-06-06 18:58:06.794203'},
 {'Nome do Produto': 'Corretivo',
  'Categoria do Produto': 'Roupas',
  'Preço do Produto (R$)': '11.96',
  'Quantidade em Estoque': '7',
  'Filial': 'Filial 6',
  'Data da Venda': '2023-03-25 18:58:06.794203'},

In [77]:
nomes_colunas = list(combined_list[0].keys())
nomes_colunas

['Nome do Produto',
 'Categoria do Produto',
 'Preço do Produto (R$)',
 'Quantidade em Estoque',
 'Filial']

In [90]:
path_dados_combinados = '/home/fe/Documentos/Git/Engenharia-de-Dados/Pipeline Dados/Data Processed/dados_combinados.csv'

with open(path_dados_combinados, 'w') as file:
    writer = csv.DictWriter(file, fieldnames=nomes_colunas)
    writer.writeheader()

    for linha in combined_list:
        writer.writerow(linha)

#Erro devido a coluna 'Data da Venda'

ValueError: dict contains fields not in fieldnames: 'Data da Venda'

### Tratamento da coluna 'Data da Venda' + novo formato para unir as duas tabelas

In [91]:
colunas_nomes = list(combined_list[0].keys())
colunas_nomes

['Nome do Produto',
 'Categoria do Produto',
 'Preço do Produto (R$)',
 'Quantidade em Estoque',
 'Filial',
 'Data da Venda']

In [92]:
dados_combinados = [colunas_nomes]

for row in combined_list:
    linha = []
    for coluna in colunas_nomes:
        print(row.get(coluna))
        linha.append(row.get(coluna, "Indisponivel"))
    dados_combinados.append(linha)
dados_combinados

Lápis de sobrancelha
Roupas
55.17
62
Filial 1
2023-04-13 18:58:06.794203
Batom matte
Eletrônicos
74.15
48
Filial 9
2023-06-03 18:58:06.794203
Corretivo
Roupas
54.86
36
Filial 5
2023-06-08 18:58:06.794203
Delineador líquido
Roupas
91.29
1
Filial 8
2023-02-27 18:58:06.794203
Batom líquido
Roupas
44.65
52
Filial 2
2022-09-05 18:58:06.794203
Base líquida
Eletrônicos
5.22
85
Filial 3
2022-09-11 18:58:06.794203
Máscara de cílios
Eletrônicos
1.08
31
Filial 6
2023-02-08 18:58:06.794203
Corretivo
Alimentos
56.22
76
Filial 5
2022-12-08 18:58:06.794203
Batom matte
Roupas
94.01
7
Filial 2
2023-07-18 18:58:06.794203
Lápis de sobrancelha
Alimentos
51.38
4
Filial 10
2023-06-19 18:58:06.794203
Pó compacto
Eletrônicos
5.59
82
Filial 10
2023-07-19 18:58:06.794203
Pó compacto
Eletrônicos
2.65
8
Filial 3
2023-05-24 18:58:06.794203
Corretivo
Roupas
68.62
6
Filial 1
2023-01-24 18:58:06.794203
Pó compacto
Alimentos
80.94
70
Filial 6
2023-06-07 18:58:06.794203
Batom matte
Alimentos
26.79
86
Filial 9
2023-01-10 18:58:06.794203
Base líquida
Alimentos
55.08
14
Filial 5
2023-02-09 18:58:06.794203
Base líquida
Alimentos
51.34
13
Filial 2
2022-10-24 18:58:06.794203
Sombra de olhos
Alimentos
31.07
45
Filial 8
2023-03-06 18:58:06.794203
Sombra de olhos
Eletrodomésticos
78.94
44
Filial 7
2022-11-12 18:58:06.794203
Batom matte
Eletrônicos
41.15
91
Filial 9
2023-02-03 18:58:06.794203
Base líquida
Eletrônicos
44.47
39
Filial 4
2023-07-31 18:58:06.794203
Sombra de olhos
Roupas
32.8
23
Filial 3
2023-06-07 18:58:06.794203
Delineador líquido
Alimentos
90.62
70
Filial 3
2022-10-31 18:58:06.794203
Pó compacto
Eletrônicos
66.56
89
Filial 1
2023-03-04 18:58:06.794203
Delineador líquido
Eletrônicos
57.56
77
Filial 8
2023-01-27 18:58:06.794203
Batom matte
Alimentos
40.92
13
Filial 3
2023-04-25 18:58:06.794203
Delineador líquido
Eletrônicos
65.96
73
Filial 10
2022-09-20 18:58:06.794203
Lápis de sobrancelha
Roupas
87.64
25
Filial 5
2023-03-09 18:58:06.794203
Sombra de olhos
Alimentos
61.21
22
Filial 3
2023-02-06 18:58:06.794203
Delineador líquido
Eletrodomésticos
12.77
57
Filial 8
2023-05-15 18:58:06.794203
Blush em pó
Roupas
86.67
61
Filial 10
2023-07-06 18:58:06.794203
Base líquida
Eletrodomésticos
26.87
56
Filial 6
2023-07-24 18:58:06.794203
Batom líquido
Roupas
83.86
33
Filial 2
2023-05-02 18:58:06.794203
Base líquida
Eletrônicos
89.13
49
Filial 3
2023-07-07 18:58:06.794203
Base líquida
Eletrônicos
12.08
87
Filial 2
2023-04-15 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
73.5
67
Filial 4
2022-11-07 18:58:06.794203
Delineador líquido
Eletrodomésticos
90.34
76
Filial 2
2023-06-16 18:58:06.794203
Batom matte
Eletrônicos
5.74
1
Filial 4
2022-12-15 18:58:06.794203
Batom matte
Roupas
47.47
62
Filial 3
2023-02-01 18:58:06.794203
Delineador líquido
Alimentos
87.52
43
Filial 9
2023-08-22 18:58:06.794203
Delineador líquido
Alimentos
14.57
72
Filial 10
2023-05-20 18:58:06.794203
Corretivo
Roupas
69.69
9
Filial 8
2023-02-03 18:58:06.794203
Batom matte
Eletrônicos
62.96
12
Filial 5
2023-05-02 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
52.49
57
Filial 1
2023-03-10 18:58:06.794203
Sombra de olhos
Roupas
85.51
5
Filial 5
2023-04-17 18:58:06.794203
Base líquida
Roupas
8.72
48
Filial 5
2023-05-16 18:58:06.794203
Batom líquido
Eletrodomésticos
78.58
89
Filial 10
2022-12-16 18:58:06.794203
Batom matte
Eletrônicos
23.8
28
Filial 9
2022-10-14 18:58:06.794203
Lápis de sobrancelha
Eletrodomésticos
36.96
5
Filial 3
2022-11-05 18:58:06.794203
Batom matte
Eletrônicos
13.84
2
Filial 6
2023-04-30 18:58:06.794203
Base líquida
Eletrodomésticos
23.45
69
Filial 7
2023-04-28 18:58:06.794203
Corretivo
Eletrônicos
31.88
19
Filial 3
2023-02-15 18:58:06.794203
Máscara de cílios
Eletrodomésticos
73.9
83
Filial 3
2023-07-02 18:58:06.794203
Batom líquido
Roupas
48.62
32
Filial 5
2023-05-27 18:58:06.794203
Batom matte
Eletrodomésticos
46.32
52
Filial 8
2023-04-12 18:58:06.794203
Base líquida
Alimentos
6.9
10
Filial 4
2023-03-23 18:58:06.794203
Pó compacto
Eletrodomésticos
26.51
10
Filial 2
2022-10-27 18:58:06.794203
Máscara de cílios
Roupas
37.52
55
Filial 9
2023-02-13 18:58:06.794203
Lápis de sobrancelha
Roupas
18.37
29
Filial 9
2023-01-01 18:58:06.794203
Sombra de olhos
Alimentos
75.04
90
Filial 3
2023-08-29 18:58:06.794203
Pó compacto
Alimentos
9.59
46
Filial 8
2023-03-31 18:58:06.794203
Corretivo
Eletrônicos
84.24
27
Filial 5
2023-03-07 18:58:06.794203
Base líquida
Eletrodomésticos
22.41
97
Filial 2
2022-09-11 18:58:06.794203
Lápis de sobrancelha
Roupas
18.03
7
Filial 10
2023-01-26 18:58:06.794203
Batom matte
Eletrônicos
56.88
49
Filial 2
2023-02-01 18:58:06.794203
Pó compacto
Eletrônicos
71.07
10
Filial 4
2023-01-01 18:58:06.794203
Corretivo
Alimentos
80.43
2
Filial 10
2023-08-03 18:58:06.794203
Batom líquido
Eletrônicos
67.95
50
Filial 10
2022-10-06 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
15.85
89
Filial 9
2023-01-09 18:58:06.794203
Sombra de olhos
Alimentos
39.86
31
Filial 7
2023-07-02 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
14.98
40
Filial 3
2023-06-04 18:58:06.794203
Corretivo
Roupas
6.9
91
Filial 9
2023-02-23 18:58:06.794203
Batom matte
Roupas
57.28
10
Filial 3
2023-07-31 18:58:06.794203
Corretivo
Eletrodomésticos
11.71
77
Filial 6
2022-11-18 18:58:06.794203
Blush em pó
Eletrodomésticos
60.0
23
Filial 2
2022-11-19 18:58:06.794203
Sombra de olhos
Eletrônicos
94.51
72
Filial 8
2023-01-14 18:58:06.794203
Sombra de olhos
Alimentos
86.96
89
Filial 7
2022-11-25 18:58:06.794203
Máscara de cílios
Eletrônicos
36.37
50
Filial 1
2022-09-29 18:58:06.794203
Sombra de olhos
Eletrônicos
9.36
72
Filial 5
2023-07-21 18:58:06.794203
Delineador líquido
Eletrodomésticos
43.3
78
Filial 6
2023-02-11 18:58:06.794203
Batom matte
Alimentos
75.34
75
Filial 1
2023-01-02 18:58:06.794203
Sombra de olhos
Eletrônicos
40.39
84
Filial 10
2022-12-16 18:58:06.794203
Delineador líquido
Eletrodomésticos
11.05
15
Filial 2
2022-12-26 18:58:06.794203
Pó compacto
Eletrônicos
39.21
26
Filial 10
2022-12-19 18:58:06.794203
Delineador líquido
Alimentos
48.01
46
Filial 8
2023-02-14 18:58:06.794203
Máscara de cílios
Eletrodomésticos
1.65
79
Filial 8
2022-10-21 18:58:06.794203
Máscara de cílios
Eletrodomésticos
43.61
75
Filial 2
2022-09-26 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
75.25
11
Filial 3
2023-08-04 18:58:06.794203
Máscara de cílios
Alimentos
55.73
25
Filial 2
2023-06-06 18:58:06.794203
Corretivo
Roupas
11.96
7
Filial 6
2023-03-25 18:58:06.794203
Batom líquido
Alimentos
84.91
88
Filial 6
2022-09-22 18:58:06.794203
Pó compacto
Eletrodomésticos
83.6
47
Filial 2
2023-06-23 18:58:06.794203
Lápis de sobrancelha
Eletrodomésticos
87.64
22
Filial 7
2023-08-17 18:58:06.794203
Base líquida
Eletrônicos
79.79
98
Filial 5
2023-06-06 18:58:06.794203
Pó compacto
Alimentos
18.36
67
Filial 5
2022-09-12 18:58:06.794203
Batom líquido
Eletrônicos
40.28
67
Filial 3
2023-03-03 18:58:06.794203
Sombra de olhos
Eletrônicos
41.92
79
Filial 4
2023-01-29 18:58:06.794203
Pó compacto
Eletrodomésticos
48.15
82
Filial 6
2022-12-03 18:58:06.794203
Delineador líquido
Eletrodomésticos
30.29
96
Filial 6
2023-02-27 18:58:06.794203
Pó compacto
Eletrônicos
98.66
86
Filial 3
2023-07-06 18:58:06.794203
Delineador líquido
Eletrônicos
61.41
14
Filial 5
2023-07-06 18:58:06.794203
Batom matte
Alimentos
99.22
4
Filial 7
2022-11-24 18:58:06.794203
Sombra de olhos
Eletrodomésticos
61.0
28
Filial 10
2022-12-24 18:58:06.794203
Blush em pó
Eletrônicos
18.86
45
Filial 9
2023-05-14 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
33.76
97
Filial 5
2023-04-23 18:58:06.794203
Delineador líquido
Alimentos
67.41
3
Filial 9
2023-01-17 18:58:06.794203
Delineador líquido
Eletrônicos
58.3
93
Filial 3
2022-10-22 18:58:06.794203
Batom líquido
Eletrodomésticos
57.95
63
Filial 9
2022-10-28 18:58:06.794203
Base líquida
Alimentos
66.9
63
Filial 2
2023-03-13 18:58:06.794203
Corretivo
Eletrodomésticos
35.55
48
Filial 3
2023-03-08 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
51.94
55
Filial 7
2023-04-28 18:58:06.794203
Sombra de olhos
Alimentos
86.0
54
Filial 7
2023-08-06 18:58:06.794203
Máscara de cílios
Eletrônicos
73.84
27
Filial 3
2023-02-19 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
34.84
55
Filial 5
2022-11-01 18:58:06.794203
Batom líquido
Roupas
41.5
72
Filial 6
2023-03-18 18:58:06.794203
Lápis de sobrancelha
Roupas
92.31
50
Filial 6
2023-03-10 18:58:06.794203
Delineador líquido
Eletrodomésticos
20.64
18
Filial 2
2022-10-09 18:58:06.794203
Batom líquido
Alimentos
94.09
81
Filial 7
2022-12-14 18:58:06.794203
Máscara de cílios
Eletrodomésticos
60.69
47
Filial 5
2022-11-14 18:58:06.794203
Máscara de cílios
Roupas
11.55
5
Filial 1
2022-11-21 18:58:06.794203
Corretivo
Roupas
95.51
56
Filial 8
2022-11-21 18:58:06.794203
Máscara de cílios
Eletrônicos
89.33
8
Filial 8
2023-06-19 18:58:06.794203
Batom líquido
Eletrônicos
49.56
38
Filial 9
2022-11-25 18:58:06.794203
Delineador líquido
Alimentos
98.97
30
Filial 4
2023-08-30 18:58:06.794203
Sombra de olhos
Eletrodomésticos
89.56
85
Filial 3
2022-09-10 18:58:06.794203
Base líquida
Eletrodomésticos
77.81
20
Filial 3
2023-01-20 18:58:06.794203
Base líquida
Alimentos
75.06
24
Filial 3
2023-06-21 18:58:06.794203
Batom líquido
Eletrodomésticos
88.5
8
Filial 8
2023-09-05 18:58:06.794203
Corretivo
Eletrônicos
17.84
59
Filial 1
2022-09-30 18:58:06.794203
Base líquida
Alimentos
64.88
81
Filial 8
2023-04-02 18:58:06.794203
Batom matte
Alimentos
69.6
25
Filial 4
2023-03-19 18:58:06.794203
Corretivo
Roupas
24.02
85
Filial 2
2022-12-27 18:58:06.794203
Pó compacto
Roupas
67.19
63
Filial 2
2023-01-13 18:58:06.794203
Corretivo
Roupas
67.23
28
Filial 6
2022-10-30 18:58:06.794203
Blush em pó
Alimentos
86.85
40
Filial 9
2022-10-07 18:58:06.794203
Lápis de sobrancelha
Roupas
41.75
98
Filial 9
2023-07-25 18:58:06.794203
Pó compacto
Roupas
52.42
38
Filial 3
2022-11-20 18:58:06.794203
Delineador líquido
Alimentos
17.13
99
Filial 9
2022-12-04 18:58:06.794203
Blush em pó
Eletrodomésticos
22.72
51
Filial 7
2023-06-28 18:58:06.794203
Máscara de cílios
Roupas
35.28
69
Filial 8
2023-02-23 18:58:06.794203
Blush em pó
Roupas
46.76
63
Filial 8
2023-07-02 18:58:06.794203
Pó compacto
Roupas
41.45
74
Filial 2
2023-02-02 18:58:06.794203
Base líquida
Roupas
93.51
69
Filial 4
2023-03-12 18:58:06.794203
Blush em pó
Eletrônicos
88.99
17
Filial 6
2023-06-22 18:58:06.794203
Delineador líquido
Alimentos
1.1
22
Filial 10
2022-10-23 18:58:06.794203
Delineador líquido
Roupas
58.94
23
Filial 9
2023-04-17 18:58:06.794203
Sombra de olhos
Eletrônicos
76.57
87
Filial 8
2022-12-05 18:58:06.794203
Batom líquido
Eletrônicos
22.91
49
Filial 9
2023-07-28 18:58:06.794203
Corretivo
Roupas
28.89
33
Filial 6
2022-09-27 18:58:06.794203
Blush em pó
Alimentos
33.57
22
Filial 9
2022-09-05 18:58:06.794203
Delineador líquido
Eletrônicos
4.12
46
Filial 2
2023-08-07 18:58:06.794203
Blush em pó
Alimentos
73.13
66
Filial 9
2023-04-23 18:58:06.794203
Base líquida
Eletrodomésticos
1.69
21
Filial 3
2022-11-20 18:58:06.794203
Pó compacto
Alimentos
27.18
24
Filial 8
2023-02-01 18:58:06.794203
Batom matte
Eletrônicos
94.47
77
Filial 8
2023-07-03 18:58:06.794203
Corretivo
Alimentos
67.19
76
Filial 1
2023-04-10 18:58:06.794203
Sombra de olhos
Alimentos
92.72
62
Filial 4
2022-12-08 18:58:06.794203
Blush em pó
Roupas
78.29
67
Filial 5
2022-10-09 18:58:06.794203
Delineador líquido
Roupas
83.18
15
Filial 1
2022-12-21 18:58:06.794203
Pó compacto
Alimentos
75.77
26
Filial 9
2023-03-07 18:58:06.794203
Batom líquido
Roupas
81.71
90
Filial 4
2023-07-25 18:58:06.794203
Batom matte
Roupas
20.73
49
Filial 6
2023-08-11 18:58:06.794203
Lápis de sobrancelha
Roupas
57.12
10
Filial 6
2023-08-11 18:58:06.794203
Delineador líquido
Roupas
29.61
15
Filial 5
2023-01-24 18:58:06.794203
Pó compacto
Alimentos
71.75
31
Filial 10
2023-07-26 18:58:06.794203
Lápis de sobrancelha
Roupas
84.33
26
Filial 6
2022-11-29 18:58:06.794203
Máscara de cílios
Eletrodomésticos
17.9
33
Filial 7
2023-01-28 18:58:06.794203
Corretivo
Alimentos
62.61
34
Filial 6
2023-04-13 18:58:06.794203
Delineador líquido
Roupas
9.21
95
Filial 10
2023-04-29 18:58:06.794203
Máscara de cílios
Eletrodomésticos
21.71
77
Filial 2
2022-11-20 18:58:06.794203
Máscara de cílios
Eletrônicos
34.76
51
Filial 4
2023-04-09 18:58:06.794203
Delineador líquido
Eletrônicos
61.77
41
Filial 3
2023-08-05 18:58:06.794203
Corretivo
Eletrônicos
29.04
21
Filial 1
2023-04-10 18:58:06.794203
Base líquida
Alimentos
32.33
6
Filial 8
2023-05-06 18:58:06.794203
Batom matte
Eletrodomésticos
25.68
33
Filial 3
2023-05-24 18:58:06.794203
Máscara de cílios
Eletrônicos
6.8
8
Filial 2
2023-01-19 18:58:06.794203
Sombra de olhos
Eletrônicos
85.55
33
Filial 2
2022-10-30 18:58:06.794203
Batom matte
Roupas
61.23
80
Filial 6
2023-04-05 18:58:06.794203
Corretivo
Eletrônicos
7.43
18
Filial 1
2022-10-27 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
92.77
18
Filial 6
2023-02-05 18:58:06.794203
Delineador líquido
Eletrônicos
70.44
79
Filial 5
2023-02-19 18:58:06.794203
Corretivo
Eletrodomésticos
98.45
14
Filial 7
2022-11-27 18:58:06.794203
Delineador líquido
Roupas
12.18
59
Filial 10
2023-07-12 18:58:06.794203
Base líquida
Eletrodomésticos
71.31
84
Filial 2
2023-07-19 18:58:06.794203
Máscara de cílios
Eletrônicos
54.71
62
Filial 5
2023-06-02 18:58:06.794203
Corretivo
Roupas
45.12
10
Filial 3
2023-04-25 18:58:06.794203
Blush em pó
Roupas
32.26
60
Filial 8
2023-03-25 18:58:06.794203
Pó compacto
Alimentos
86.78
24
Filial 6
2022-12-13 18:58:06.794203
Blush em pó
Eletrodomésticos
71.86
26
Filial 10
2023-06-02 18:58:06.794203
Pó compacto
Eletrônicos
45.38
41
Filial 5
2023-05-25 18:58:06.794203
Corretivo
Roupas
53.76
27
Filial 4
2023-03-05 18:58:06.794203
Batom líquido
Eletrodomésticos
7.41
93
Filial 6
2023-01-18 18:58:06.794203
Batom matte
Eletrônicos
68.97
79
Filial 3
2023-03-15 18:58:06.794203
Blush em pó
Eletrodomésticos
10.5
80
Filial 6
2023-07-26 18:58:06.794203
Corretivo
Alimentos
67.79
19
Filial 5
2023-09-05 18:58:06.794203
Máscara de cílios
Eletrodomésticos
73.11
62
Filial 1
2023-04-05 18:58:06.794203
Sombra de olhos
Eletrônicos
93.33
99
Filial 8
2023-04-17 18:58:06.794203
Blush em pó
Roupas
86.79
100
Filial 5
2023-03-23 18:58:06.794203
Lápis de sobrancelha
Roupas
4.92
62
Filial 5
2022-11-03 18:58:06.794203
Sombra de olhos
Roupas
40.14
45
Filial 9
2023-03-01 18:58:06.794203
Blush em pó
Alimentos
75.09
19
Filial 1
2023-05-29 18:58:06.794203
Lápis de sobrancelha
Roupas
30.61
43
Filial 9
2023-03-22 18:58:06.794203
Pó compacto
Alimentos
25.94
61
Filial 1
2023-07-05 18:58:06.794203
Batom líquido
Eletrônicos
51.59
47
Filial 3
2022-11-14 18:58:06.794203
Base líquida
Alimentos
67.69
35
Filial 2
2022-11-20 18:58:06.794203
Máscara de cílios
Eletrônicos
71.22
72
Filial 10
2023-07-23 18:58:06.794203
Pó compacto
Eletrônicos
31.11
93
Filial 6
2023-04-14 18:58:06.794203
Pó compacto
Eletrodomésticos
4.39
29
Filial 8
2023-02-18 18:58:06.794203
Corretivo
Eletrodomésticos
43.63
47
Filial 9
2023-02-23 18:58:06.794203
Delineador líquido
Alimentos
26.15
33
Filial 9
2022-12-16 18:58:06.794203
Pó compacto
Alimentos
98.99
1
Filial 6
2023-06-09 18:58:06.794203
Máscara de cílios
Roupas
17.66
39
Filial 6
2022-12-11 18:58:06.794203
Base líquida
Alimentos
53.44
67
Filial 5
2022-09-18 18:58:06.794203
Batom matte
Eletrodomésticos
16.29
19
Filial 7
2022-11-27 18:58:06.794203
Lápis de sobrancelha
Eletrônicos
13.8
19
Filial 2
2022-12-09 18:58:06.794203
Blush em pó
Roupas
26.5
12
Filial 10
2023-06-11 18:58:06.794203
Batom líquido
Alimentos
31.78
72
Filial 5
2022-09-10 18:58:06.794203
Base líquida
Roupas
85.44
77
Filial 9
2023-08-21 18:58:06.794203
Delineador líquido
Alimentos
85.49
11
Filial 1
2022-11-19 18:58:06.794203
Batom líquido
Eletrônicos
73.44
96
Filial 7
2023-06-05 18:58:06.794203
Máscara de cílios
Roupas
32.67
12
Filial 8
2022-11-06 18:58:06.794203
Blush em pó
Alimentos
25.04
89
Filial 10
2022-10-05 18:58:06.794203
Delineador líquido
Roupas
36.61
53
Filial 10
2022-11-10 18:58:06.794203
Base líquida
Eletrônicos
13.47
80
Filial 9
2023-08-23 18:58:06.794203
Lápis de sobrancelha
Eletrodomésticos
72.95
10
Filial 7
2022-12-01 18:58:06.794203
Batom líquido
Eletrodomésticos
65.8
77
Filial 9
2023-02-11 18:58:06.794203
Pó compacto
Eletrônicos
57.42
49
Filial 6
2022-12-02 18:58:06.794203
Base líquida
Alimentos
15.26
42
Filial 8
2023-03-24 18:58:06.794203
Lápis de sobrancelha
Roupas
93.2
91
Filial 7
2023-03-29 18:58:06.794203
Blush em pó
Roupas
62.62
78
Filial 5
2023-05-02 18:58:06.794203
Delineador líquido
Alimentos
28.07
70
Filial 2
2022-10-01 18:58:06.794203
Lápis de sobrancelha
Eletrodomésticos
47.69
46
Filial 2
2023-08-19 18:58:06.794203
Blush em pó
Alimentos
40.39
54
Filial 7
2022-10-06 18:58:06.794203
Batom matte
Eletrônicos
98.6
92
Filial 3
2022-12-31 18:58:06.794203
Delineador líquido
Eletrodomésticos
41.29
16
Filial 7
2023-06-01 18:58:06.794203
Sombra de olhos
Eletrodomésticos
74.29
20
Filial 7
2023-05-12 18:58:06.794203
Sombra de olhos
Alimentos
58.71
43
Filial 10
2022-12-02 18:58:06.794203
Batom matte
Eletrodomésticos
3.6
2
Filial 1
2023-07-25 18:58:06.794203
Blush em pó
Alimentos
21.08
67
Filial 4
2022-11-10 18:58:06.794203
Pó compacto
Roupas
63.62
36
Filial 3
2022-12-14 18:58:06.794203
Batom matte
Eletrodomésticos
8.66
25
Filial 4
2023-07-03 18:58:06.794203
Pó compacto
Alimentos
79.56
85
Filial 5
2023-05-29 18:58:06.794203
Delineador líquido
Alimentos
17.56
64
Filial 2
2022-10-18 18:58:06.794203
Blush em pó
Roupas
84.64
4
Filial 5
2022-11-18 18:58:06.794203
Corretivo
Eletrodomésticos
42.59
20
Filial 8
2022-10-05 18:58:06.794203
Lápis de sobrancelha
Alimentos
78.5
49
Filial 9
2023-06-12 18:58:06.794203
Sombra de olhos
Eletrodomésticos
97.49
7
Filial 3
2022-11-14 18:58:06.794203
Corretivo
Eletrodomésticos
49.08
31
Filial 1
2023-03-05 18:58:06.794203
Máscara de cílios
Alimentos
67.99
98
Filial 8
2023-02-01 18:58:06.794203
Batom líquido
Alimentos
71.63
61
Filial 3
2022-10-04 18:58:06.794203
Máscara de cílios
Alimentos
73.04
12
Filial 8
2022-09-11 18:58:06.794203
Delineador líquido
Eletrodomésticos
66.35
44
Filial 10
2023-01-11 18:58:06.794203
Blush em pó
Eletrodomésticos
89.05
31
Filial 5
2022-12-21 18:58:06.794203
Delineador líquido
Roupas
6.07
65
Filial 3
2022-12-14 18:58:06.794203
Máscara de cílios
Eletrodomésticos
15.38
18
Filial 1
2022-12-11 18:58:06.794203
Base líquida
Eletrônicos
12.27
23
Filial 9
2023-05-08 18:58:06.794203
Batom líquido
Alimentos
77.02
85
Filial 8
2022-10-18 18:58:06.794203
Base líquida
Roupas
68.69
32
Filial 8
2022-12-26 18:58:06.794203
Batom líquido
Eletrodomésticos
55.96
42
Filial 7
2022-10-18 18:58:06.794203
Corretivo
Eletrodomésticos
54.17
78
Filial 1
2023-02-22 18:58:06.794203
Pó compacto
Alimentos
52.67
64
Filial 1
2023-09-03 18:58:06.794203
Base líquida
Roupas
32.47
28
Filial 2
2022-11-25 18:58:06.794203
Batom matte
Roupas
71.09
62
Filial 7
2023-06-01 18:58:06.794203
Lápis de sobrancelha
Eletrodomésticos
24.2
43
Filial 10
2023-02-28 18:58:06.794203
Pó compacto
Roupas
42.15
11
Filial 3
2023-03-07 18:58:06.794203
Pó compacto
Eletrodomésticos
15.97
31
Filial 2
2023-05-18 18:58:06.794203
Base líquida
Roupas
54.79
62
Filial 2
2022-11-15 18:58:06.794203
Pó compacto
Alimentos
7.21
96
Filial 1
2023-08-23 18:58:06.794203
Corretivo
Eletrodomésticos
12.53
23
Filial 5
2023-01-26 18:58:06.794203
Máscara de cílios
Roupas
22.32
86
Filial 1
2023-06-25 18:58:06.794203
Sombra de olhos
Alimentos
10.73
45
Filial 5
2023-05-17 18:58:06.794203
Máscara de cílios
Roupas
91.29
18
Filial 3
2022-12-18 18:58:06.794203
Sombra de olhos
Alimentos
56.98
66
Filial 9
2023-01-23 18:58:06.794203
Sombra de olhos
Eletrodomésticos
14.73
44
Filial 7
2022-09-10 18:58:06.794203
Blush em pó
Eletrônicos
73.65
72
Filial 3
2022-10-04 18:58:06.794203
Blush em pó
Roupas
67.49
5
Filial 10
2022-12-02 18:58:06.794203
Corretivo
Eletrônicos
83.97
44
Filial 7
2022-09-18 18:58:06.794203
Corretivo
Eletrônicos
35.47
40
Filial 1
2023-01-19 18:58:06.794203
Máscara de cílios
Roupas
45.83
96
Filial 8
2022-10-15 18:58:06.794203
Pó compacto
Eletrônicos
66.22
81
Filial 5
2023-09-04 18:58:06.794203
Delineador líquido
Eletrodomésticos
10.18
34
Filial 5
2022-12-26 18:58:06.794203
Delineador líquido
Alimentos
98.0
10
Filial 5

[['Nome do Produto',
  'Categoria do Produto',
  'Preço do Produto (R$)',
  'Quantidade em Estoque',
  'Filial',
  'Data da Venda'],
 ['Lápis de sobrancelha',
  'Roupas',
  '55.17',
  '62',
  'Filial 1',
  '2023-04-13 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '74.15',
  '48',
  'Filial 9',
  '2023-06-03 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '54.86',
  '36',
  'Filial 5',
  '2023-06-08 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '91.29',
  '1',
  'Filial 8',
  '2023-02-27 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '44.65',
  '52',
  'Filial 2',
  '2022-09-05 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '5.22',
  '85',
  'Filial 3',
  '2022-09-11 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '1.08',
  '31',
  'Filial 6',
  '2023-02-08 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '56.22',
  '76',
  'Filial 5',
  '2022-12-08 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '94.01',
  '7',
  'Filial 2',
  '2023-07-18 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Alimentos',
  '51.38',
  '4',
  'Filial 10',
  '2023-06-19 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '5.59',
  '82',
  'Filial 10',
  '2023-07-19 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '2.65',
  '8',
  'Filial 3',
  '2023-05-24 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '68.62',
  '6',
  'Filial 1',
  '2023-01-24 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '80.94',
  '70',
  'Filial 6',
  '2023-06-07 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '26.79',
  '86',
  'Filial 9',
  '2023-01-10 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '55.08',
  '14',
  'Filial 5',
  '2023-02-09 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '51.34',
  '13',
  'Filial 2',
  '2022-10-24 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '31.07',
  '45',
  'Filial 8',
  '2023-03-06 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '78.94',
  '44',
  'Filial 7',
  '2022-11-12 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '41.15',
  '91',
  'Filial 9',
  '2023-02-03 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '44.47',
  '39',
  'Filial 4',
  '2023-07-31 18:58:06.794203'],
 ['Sombra de olhos',
  'Roupas',
  '32.8',
  '23',
  'Filial 3',
  '2023-06-07 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '90.62',
  '70',
  'Filial 3',
  '2022-10-31 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '66.56',
  '89',
  'Filial 1',
  '2023-03-04 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '57.56',
  '77',
  'Filial 8',
  '2023-01-27 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '40.92',
  '13',
  'Filial 3',
  '2023-04-25 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '65.96',
  '73',
  'Filial 10',
  '2022-09-20 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '87.64',
  '25',
  'Filial 5',
  '2023-03-09 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '61.21',
  '22',
  'Filial 3',
  '2023-02-06 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '12.77',
  '57',
  'Filial 8',
  '2023-05-15 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '86.67',
  '61',
  'Filial 10',
  '2023-07-06 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '26.87',
  '56',
  'Filial 6',
  '2023-07-24 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '83.86',
  '33',
  'Filial 2',
  '2023-05-02 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '89.13',
  '49',
  'Filial 3',
  '2023-07-07 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '12.08',
  '87',
  'Filial 2',
  '2023-04-15 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '73.5',
  '67',
  'Filial 4',
  '2022-11-07 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '90.34',
  '76',
  'Filial 2',
  '2023-06-16 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '5.74',
  '1',
  'Filial 4',
  '2022-12-15 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '47.47',
  '62',
  'Filial 3',
  '2023-02-01 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '87.52',
  '43',
  'Filial 9',
  '2023-08-22 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '14.57',
  '72',
  'Filial 10',
  '2023-05-20 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '69.69',
  '9',
  'Filial 8',
  '2023-02-03 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '62.96',
  '12',
  'Filial 5',
  '2023-05-02 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '52.49',
  '57',
  'Filial 1',
  '2023-03-10 18:58:06.794203'],
 ['Sombra de olhos',
  'Roupas',
  '85.51',
  '5',
  'Filial 5',
  '2023-04-17 18:58:06.794203'],
 ['Base líquida',
  'Roupas',
  '8.72',
  '48',
  'Filial 5',
  '2023-05-16 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '78.58',
  '89',
  'Filial 10',
  '2022-12-16 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '23.8',
  '28',
  'Filial 9',
  '2022-10-14 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrodomésticos',
  '36.96',
  '5',
  'Filial 3',
  '2022-11-05 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '13.84',
  '2',
  'Filial 6',
  '2023-04-30 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '23.45',
  '69',
  'Filial 7',
  '2023-04-28 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '31.88',
  '19',
  'Filial 3',
  '2023-02-15 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '73.9',
  '83',
  'Filial 3',
  '2023-07-02 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '48.62',
  '32',
  'Filial 5',
  '2023-05-27 18:58:06.794203'],
 ['Batom matte',
  'Eletrodomésticos',
  '46.32',
  '52',
  'Filial 8',
  '2023-04-12 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '6.9',
  '10',
  'Filial 4',
  '2023-03-23 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '26.51',
  '10',
  'Filial 2',
  '2022-10-27 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '37.52',
  '55',
  'Filial 9',
  '2023-02-13 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '18.37',
  '29',
  'Filial 9',
  '2023-01-01 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '75.04',
  '90',
  'Filial 3',
  '2023-08-29 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '9.59',
  '46',
  'Filial 8',
  '2023-03-31 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '84.24',
  '27',
  'Filial 5',
  '2023-03-07 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '22.41',
  '97',
  'Filial 2',
  '2022-09-11 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '18.03',
  '7',
  'Filial 10',
  '2023-01-26 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '56.88',
  '49',
  'Filial 2',
  '2023-02-01 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '71.07',
  '10',
  'Filial 4',
  '2023-01-01 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '80.43',
  '2',
  'Filial 10',
  '2023-08-03 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '67.95',
  '50',
  'Filial 10',
  '2022-10-06 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '15.85',
  '89',
  'Filial 9',
  '2023-01-09 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '39.86',
  '31',
  'Filial 7',
  '2023-07-02 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '14.98',
  '40',
  'Filial 3',
  '2023-06-04 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '6.9',
  '91',
  'Filial 9',
  '2023-02-23 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '57.28',
  '10',
  'Filial 3',
  '2023-07-31 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '11.71',
  '77',
  'Filial 6',
  '2022-11-18 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '60.0',
  '23',
  'Filial 2',
  '2022-11-19 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '94.51',
  '72',
  'Filial 8',
  '2023-01-14 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '86.96',
  '89',
  'Filial 7',
  '2022-11-25 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '36.37',
  '50',
  'Filial 1',
  '2022-09-29 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '9.36',
  '72',
  'Filial 5',
  '2023-07-21 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '43.3',
  '78',
  'Filial 6',
  '2023-02-11 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '75.34',
  '75',
  'Filial 1',
  '2023-01-02 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '40.39',
  '84',
  'Filial 10',
  '2022-12-16 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '11.05',
  '15',
  'Filial 2',
  '2022-12-26 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '39.21',
  '26',
  'Filial 10',
  '2022-12-19 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '48.01',
  '46',
  'Filial 8',
  '2023-02-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '1.65',
  '79',
  'Filial 8',
  '2022-10-21 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '43.61',
  '75',
  'Filial 2',
  '2022-09-26 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '75.25',
  '11',
  'Filial 3',
  '2023-08-04 18:58:06.794203'],
 ['Máscara de cílios',
  'Alimentos',
  '55.73',
  '25',
  'Filial 2',
  '2023-06-06 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '11.96',
  '7',
  'Filial 6',
  '2023-03-25 18:58:06.794203'],
 ['Batom líquido',
  'Alimentos',
  '84.91',
  '88',
  'Filial 6',
  '2022-09-22 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '83.6',
  '47',
  'Filial 2',
  '2023-06-23 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrodomésticos',
  '87.64',
  '22',
  'Filial 7',
  '2023-08-17 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '79.79',
  '98',
  'Filial 5',
  '2023-06-06 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '18.36',
  '67',
  'Filial 5',
  '2022-09-12 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '40.28',
  '67',
  'Filial 3',
  '2023-03-03 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '41.92',
  '79',
  'Filial 4',
  '2023-01-29 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '48.15',
  '82',
  'Filial 6',
  '2022-12-03 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '30.29',
  '96',
  'Filial 6',
  '2023-02-27 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '98.66',
  '86',
  'Filial 3',
  '2023-07-06 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '61.41',
  '14',
  'Filial 5',
  '2023-07-06 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '99.22',
  '4',
  'Filial 7',
  '2022-11-24 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '61.0',
  '28',
  'Filial 10',
  '2022-12-24 18:58:06.794203'],
 ['Blush em pó',
  'Eletrônicos',
  '18.86',
  '45',
  'Filial 9',
  '2023-05-14 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '33.76',
  '97',
  'Filial 5',
  '2023-04-23 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '67.41',
  '3',
  'Filial 9',
  '2023-01-17 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '58.3',
  '93',
  'Filial 3',
  '2022-10-22 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '57.95',
  '63',
  'Filial 9',
  '2022-10-28 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '66.9',
  '63',
  'Filial 2',
  '2023-03-13 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '35.55',
  '48',
  'Filial 3',
  '2023-03-08 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '51.94',
  '55',
  'Filial 7',
  '2023-04-28 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '86.0',
  '54',
  'Filial 7',
  '2023-08-06 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '73.84',
  '27',
  'Filial 3',
  '2023-02-19 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '34.84',
  '55',
  'Filial 5',
  '2022-11-01 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '41.5',
  '72',
  'Filial 6',
  '2023-03-18 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '92.31',
  '50',
  'Filial 6',
  '2023-03-10 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '20.64',
  '18',
  'Filial 2',
  '2022-10-09 18:58:06.794203'],
 ['Batom líquido',
  'Alimentos',
  '94.09',
  '81',
  'Filial 7',
  '2022-12-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '60.69',
  '47',
  'Filial 5',
  '2022-11-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '11.55',
  '5',
  'Filial 1',
  '2022-11-21 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '95.51',
  '56',
  'Filial 8',
  '2022-11-21 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '89.33',
  '8',
  'Filial 8',
  '2023-06-19 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '49.56',
  '38',
  'Filial 9',
  '2022-11-25 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '98.97',
  '30',
  'Filial 4',
  '2023-08-30 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '89.56',
  '85',
  'Filial 3',
  '2022-09-10 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '77.81',
  '20',
  'Filial 3',
  '2023-01-20 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '75.06',
  '24',
  'Filial 3',
  '2023-06-21 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '88.5',
  '8',
  'Filial 8',
  '2023-09-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '17.84',
  '59',
  'Filial 1',
  '2022-09-30 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '64.88',
  '81',
  'Filial 8',
  '2023-04-02 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '69.6',
  '25',
  'Filial 4',
  '2023-03-19 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '24.02',
  '85',
  'Filial 2',
  '2022-12-27 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '67.19',
  '63',
  'Filial 2',
  '2023-01-13 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '67.23',
  '28',
  'Filial 6',
  '2022-10-30 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '86.85',
  '40',
  'Filial 9',
  '2022-10-07 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '41.75',
  '98',
  'Filial 9',
  '2023-07-25 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '52.42',
  '38',
  'Filial 3',
  '2022-11-20 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '17.13',
  '99',
  'Filial 9',
  '2022-12-04 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '22.72',
  '51',
  'Filial 7',
  '2023-06-28 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '35.28',
  '69',
  'Filial 8',
  '2023-02-23 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '46.76',
  '63',
  'Filial 8',
  '2023-07-02 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '41.45',
  '74',
  'Filial 2',
  '2023-02-02 18:58:06.794203'],
 ['Base líquida',
  'Roupas',
  '93.51',
  '69',
  'Filial 4',
  '2023-03-12 18:58:06.794203'],
 ['Blush em pó',
  'Eletrônicos',
  '88.99',
  '17',
  'Filial 6',
  '2023-06-22 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '1.1',
  '22',
  'Filial 10',
  '2022-10-23 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '58.94',
  '23',
  'Filial 9',
  '2023-04-17 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '76.57',
  '87',
  'Filial 8',
  '2022-12-05 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '22.91',
  '49',
  'Filial 9',
  '2023-07-28 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '28.89',
  '33',
  'Filial 6',
  '2022-09-27 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '33.57',
  '22',
  'Filial 9',
  '2022-09-05 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '4.12',
  '46',
  'Filial 2',
  '2023-08-07 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '73.13',
  '66',
  'Filial 9',
  '2023-04-23 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '1.69',
  '21',
  'Filial 3',
  '2022-11-20 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '27.18',
  '24',
  'Filial 8',
  '2023-02-01 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '94.47',
  '77',
  'Filial 8',
  '2023-07-03 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '67.19',
  '76',
  'Filial 1',
  '2023-04-10 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '92.72',
  '62',
  'Filial 4',
  '2022-12-08 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '78.29',
  '67',
  'Filial 5',
  '2022-10-09 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '83.18',
  '15',
  'Filial 1',
  '2022-12-21 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '75.77',
  '26',
  'Filial 9',
  '2023-03-07 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '81.71',
  '90',
  'Filial 4',
  '2023-07-25 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '20.73',
  '49',
  'Filial 6',
  '2023-08-11 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '57.12',
  '10',
  'Filial 6',
  '2023-08-11 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '29.61',
  '15',
  'Filial 5',
  '2023-01-24 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '71.75',
  '31',
  'Filial 10',
  '2023-07-26 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '84.33',
  '26',
  'Filial 6',
  '2022-11-29 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '17.9',
  '33',
  'Filial 7',
  '2023-01-28 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '62.61',
  '34',
  'Filial 6',
  '2023-04-13 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '9.21',
  '95',
  'Filial 10',
  '2023-04-29 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '21.71',
  '77',
  'Filial 2',
  '2022-11-20 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '34.76',
  '51',
  'Filial 4',
  '2023-04-09 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '61.77',
  '41',
  'Filial 3',
  '2023-08-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '29.04',
  '21',
  'Filial 1',
  '2023-04-10 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '32.33',
  '6',
  'Filial 8',
  '2023-05-06 18:58:06.794203'],
 ['Batom matte',
  'Eletrodomésticos',
  '25.68',
  '33',
  'Filial 3',
  '2023-05-24 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '6.8',
  '8',
  'Filial 2',
  '2023-01-19 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '85.55',
  '33',
  'Filial 2',
  '2022-10-30 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '61.23',
  '80',
  'Filial 6',
  '2023-04-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '7.43',
  '18',
  'Filial 1',
  '2022-10-27 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '92.77',
  '18',
  'Filial 6',
  '2023-02-05 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '70.44',
  '79',
  'Filial 5',
  '2023-02-19 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '98.45',
  '14',
  'Filial 7',
  '2022-11-27 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '12.18',
  '59',
  'Filial 10',
  '2023-07-12 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '71.31',
  '84',
  'Filial 2',
  '2023-07-19 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '54.71',
  '62',
  'Filial 5',
  '2023-06-02 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '45.12',
  '10',
  'Filial 3',
  '2023-04-25 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '32.26',
  '60',
  'Filial 8',
  '2023-03-25 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '86.78',
  '24',
  'Filial 6',
  '2022-12-13 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '71.86',
  '26',
  'Filial 10',
  '2023-06-02 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '45.38',
  '41',
  'Filial 5',
  '2023-05-25 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '53.76',
  '27',
  'Filial 4',
  '2023-03-05 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '7.41',
  '93',
  'Filial 6',
  '2023-01-18 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '68.97',
  '79',
  'Filial 3',
  '2023-03-15 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '10.5',
  '80',
  'Filial 6',
  '2023-07-26 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '67.79',
  '19',
  'Filial 5',
  '2023-09-05 18:58:06.794203'],

In [93]:
path_dados_combinados= '/home/fe/Documentos/Git/Engenharia-de-Dados/Pipeline Dados/Data Processed/dados_combinados.csv'

with open(path_dados_combinados, 'w') as file:
    writer = csv.writer(file)
    writer.writerows(dados_combinados)

dados_combinados

[['Nome do Produto',
  'Categoria do Produto',
  'Preço do Produto (R$)',
  'Quantidade em Estoque',
  'Filial',
  'Data da Venda'],
 ['Lápis de sobrancelha',
  'Roupas',
  '55.17',
  '62',
  'Filial 1',
  '2023-04-13 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '74.15',
  '48',
  'Filial 9',
  '2023-06-03 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '54.86',
  '36',
  'Filial 5',
  '2023-06-08 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '91.29',
  '1',
  'Filial 8',
  '2023-02-27 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '44.65',
  '52',
  'Filial 2',
  '2022-09-05 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '5.22',
  '85',
  'Filial 3',
  '2022-09-11 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '1.08',
  '31',
  'Filial 6',
  '2023-02-08 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '56.22',
  '76',
  'Filial 5',
  '2022-12-08 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '94.01',
  '7',
  'Filial 2',
  '2023-07-18 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Alimentos',
  '51.38',
  '4',
  'Filial 10',
  '2023-06-19 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '5.59',
  '82',
  'Filial 10',
  '2023-07-19 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '2.65',
  '8',
  'Filial 3',
  '2023-05-24 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '68.62',
  '6',
  'Filial 1',
  '2023-01-24 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '80.94',
  '70',
  'Filial 6',
  '2023-06-07 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '26.79',
  '86',
  'Filial 9',
  '2023-01-10 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '55.08',
  '14',
  'Filial 5',
  '2023-02-09 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '51.34',
  '13',
  'Filial 2',
  '2022-10-24 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '31.07',
  '45',
  'Filial 8',
  '2023-03-06 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '78.94',
  '44',
  'Filial 7',
  '2022-11-12 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '41.15',
  '91',
  'Filial 9',
  '2023-02-03 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '44.47',
  '39',
  'Filial 4',
  '2023-07-31 18:58:06.794203'],
 ['Sombra de olhos',
  'Roupas',
  '32.8',
  '23',
  'Filial 3',
  '2023-06-07 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '90.62',
  '70',
  'Filial 3',
  '2022-10-31 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '66.56',
  '89',
  'Filial 1',
  '2023-03-04 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '57.56',
  '77',
  'Filial 8',
  '2023-01-27 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '40.92',
  '13',
  'Filial 3',
  '2023-04-25 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '65.96',
  '73',
  'Filial 10',
  '2022-09-20 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '87.64',
  '25',
  'Filial 5',
  '2023-03-09 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '61.21',
  '22',
  'Filial 3',
  '2023-02-06 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '12.77',
  '57',
  'Filial 8',
  '2023-05-15 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '86.67',
  '61',
  'Filial 10',
  '2023-07-06 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '26.87',
  '56',
  'Filial 6',
  '2023-07-24 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '83.86',
  '33',
  'Filial 2',
  '2023-05-02 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '89.13',
  '49',
  'Filial 3',
  '2023-07-07 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '12.08',
  '87',
  'Filial 2',
  '2023-04-15 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '73.5',
  '67',
  'Filial 4',
  '2022-11-07 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '90.34',
  '76',
  'Filial 2',
  '2023-06-16 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '5.74',
  '1',
  'Filial 4',
  '2022-12-15 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '47.47',
  '62',
  'Filial 3',
  '2023-02-01 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '87.52',
  '43',
  'Filial 9',
  '2023-08-22 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '14.57',
  '72',
  'Filial 10',
  '2023-05-20 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '69.69',
  '9',
  'Filial 8',
  '2023-02-03 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '62.96',
  '12',
  'Filial 5',
  '2023-05-02 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '52.49',
  '57',
  'Filial 1',
  '2023-03-10 18:58:06.794203'],
 ['Sombra de olhos',
  'Roupas',
  '85.51',
  '5',
  'Filial 5',
  '2023-04-17 18:58:06.794203'],
 ['Base líquida',
  'Roupas',
  '8.72',
  '48',
  'Filial 5',
  '2023-05-16 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '78.58',
  '89',
  'Filial 10',
  '2022-12-16 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '23.8',
  '28',
  'Filial 9',
  '2022-10-14 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrodomésticos',
  '36.96',
  '5',
  'Filial 3',
  '2022-11-05 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '13.84',
  '2',
  'Filial 6',
  '2023-04-30 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '23.45',
  '69',
  'Filial 7',
  '2023-04-28 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '31.88',
  '19',
  'Filial 3',
  '2023-02-15 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '73.9',
  '83',
  'Filial 3',
  '2023-07-02 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '48.62',
  '32',
  'Filial 5',
  '2023-05-27 18:58:06.794203'],
 ['Batom matte',
  'Eletrodomésticos',
  '46.32',
  '52',
  'Filial 8',
  '2023-04-12 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '6.9',
  '10',
  'Filial 4',
  '2023-03-23 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '26.51',
  '10',
  'Filial 2',
  '2022-10-27 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '37.52',
  '55',
  'Filial 9',
  '2023-02-13 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '18.37',
  '29',
  'Filial 9',
  '2023-01-01 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '75.04',
  '90',
  'Filial 3',
  '2023-08-29 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '9.59',
  '46',
  'Filial 8',
  '2023-03-31 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '84.24',
  '27',
  'Filial 5',
  '2023-03-07 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '22.41',
  '97',
  'Filial 2',
  '2022-09-11 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '18.03',
  '7',
  'Filial 10',
  '2023-01-26 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '56.88',
  '49',
  'Filial 2',
  '2023-02-01 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '71.07',
  '10',
  'Filial 4',
  '2023-01-01 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '80.43',
  '2',
  'Filial 10',
  '2023-08-03 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '67.95',
  '50',
  'Filial 10',
  '2022-10-06 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '15.85',
  '89',
  'Filial 9',
  '2023-01-09 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '39.86',
  '31',
  'Filial 7',
  '2023-07-02 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '14.98',
  '40',
  'Filial 3',
  '2023-06-04 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '6.9',
  '91',
  'Filial 9',
  '2023-02-23 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '57.28',
  '10',
  'Filial 3',
  '2023-07-31 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '11.71',
  '77',
  'Filial 6',
  '2022-11-18 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '60.0',
  '23',
  'Filial 2',
  '2022-11-19 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '94.51',
  '72',
  'Filial 8',
  '2023-01-14 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '86.96',
  '89',
  'Filial 7',
  '2022-11-25 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '36.37',
  '50',
  'Filial 1',
  '2022-09-29 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '9.36',
  '72',
  'Filial 5',
  '2023-07-21 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '43.3',
  '78',
  'Filial 6',
  '2023-02-11 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '75.34',
  '75',
  'Filial 1',
  '2023-01-02 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '40.39',
  '84',
  'Filial 10',
  '2022-12-16 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '11.05',
  '15',
  'Filial 2',
  '2022-12-26 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '39.21',
  '26',
  'Filial 10',
  '2022-12-19 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '48.01',
  '46',
  'Filial 8',
  '2023-02-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '1.65',
  '79',
  'Filial 8',
  '2022-10-21 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '43.61',
  '75',
  'Filial 2',
  '2022-09-26 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '75.25',
  '11',
  'Filial 3',
  '2023-08-04 18:58:06.794203'],
 ['Máscara de cílios',
  'Alimentos',
  '55.73',
  '25',
  'Filial 2',
  '2023-06-06 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '11.96',
  '7',
  'Filial 6',
  '2023-03-25 18:58:06.794203'],
 ['Batom líquido',
  'Alimentos',
  '84.91',
  '88',
  'Filial 6',
  '2022-09-22 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '83.6',
  '47',
  'Filial 2',
  '2023-06-23 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrodomésticos',
  '87.64',
  '22',
  'Filial 7',
  '2023-08-17 18:58:06.794203'],
 ['Base líquida',
  'Eletrônicos',
  '79.79',
  '98',
  'Filial 5',
  '2023-06-06 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '18.36',
  '67',
  'Filial 5',
  '2022-09-12 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '40.28',
  '67',
  'Filial 3',
  '2023-03-03 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '41.92',
  '79',
  'Filial 4',
  '2023-01-29 18:58:06.794203'],
 ['Pó compacto',
  'Eletrodomésticos',
  '48.15',
  '82',
  'Filial 6',
  '2022-12-03 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '30.29',
  '96',
  'Filial 6',
  '2023-02-27 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '98.66',
  '86',
  'Filial 3',
  '2023-07-06 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '61.41',
  '14',
  'Filial 5',
  '2023-07-06 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '99.22',
  '4',
  'Filial 7',
  '2022-11-24 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '61.0',
  '28',
  'Filial 10',
  '2022-12-24 18:58:06.794203'],
 ['Blush em pó',
  'Eletrônicos',
  '18.86',
  '45',
  'Filial 9',
  '2023-05-14 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '33.76',
  '97',
  'Filial 5',
  '2023-04-23 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '67.41',
  '3',
  'Filial 9',
  '2023-01-17 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '58.3',
  '93',
  'Filial 3',
  '2022-10-22 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '57.95',
  '63',
  'Filial 9',
  '2022-10-28 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '66.9',
  '63',
  'Filial 2',
  '2023-03-13 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '35.55',
  '48',
  'Filial 3',
  '2023-03-08 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '51.94',
  '55',
  'Filial 7',
  '2023-04-28 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '86.0',
  '54',
  'Filial 7',
  '2023-08-06 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '73.84',
  '27',
  'Filial 3',
  '2023-02-19 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '34.84',
  '55',
  'Filial 5',
  '2022-11-01 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '41.5',
  '72',
  'Filial 6',
  '2023-03-18 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '92.31',
  '50',
  'Filial 6',
  '2023-03-10 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrodomésticos',
  '20.64',
  '18',
  'Filial 2',
  '2022-10-09 18:58:06.794203'],
 ['Batom líquido',
  'Alimentos',
  '94.09',
  '81',
  'Filial 7',
  '2022-12-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '60.69',
  '47',
  'Filial 5',
  '2022-11-14 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '11.55',
  '5',
  'Filial 1',
  '2022-11-21 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '95.51',
  '56',
  'Filial 8',
  '2022-11-21 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '89.33',
  '8',
  'Filial 8',
  '2023-06-19 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '49.56',
  '38',
  'Filial 9',
  '2022-11-25 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '98.97',
  '30',
  'Filial 4',
  '2023-08-30 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrodomésticos',
  '89.56',
  '85',
  'Filial 3',
  '2022-09-10 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '77.81',
  '20',
  'Filial 3',
  '2023-01-20 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '75.06',
  '24',
  'Filial 3',
  '2023-06-21 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '88.5',
  '8',
  'Filial 8',
  '2023-09-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '17.84',
  '59',
  'Filial 1',
  '2022-09-30 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '64.88',
  '81',
  'Filial 8',
  '2023-04-02 18:58:06.794203'],
 ['Batom matte',
  'Alimentos',
  '69.6',
  '25',
  'Filial 4',
  '2023-03-19 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '24.02',
  '85',
  'Filial 2',
  '2022-12-27 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '67.19',
  '63',
  'Filial 2',
  '2023-01-13 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '67.23',
  '28',
  'Filial 6',
  '2022-10-30 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '86.85',
  '40',
  'Filial 9',
  '2022-10-07 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '41.75',
  '98',
  'Filial 9',
  '2023-07-25 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '52.42',
  '38',
  'Filial 3',
  '2022-11-20 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '17.13',
  '99',
  'Filial 9',
  '2022-12-04 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '22.72',
  '51',
  'Filial 7',
  '2023-06-28 18:58:06.794203'],
 ['Máscara de cílios',
  'Roupas',
  '35.28',
  '69',
  'Filial 8',
  '2023-02-23 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '46.76',
  '63',
  'Filial 8',
  '2023-07-02 18:58:06.794203'],
 ['Pó compacto',
  'Roupas',
  '41.45',
  '74',
  'Filial 2',
  '2023-02-02 18:58:06.794203'],
 ['Base líquida',
  'Roupas',
  '93.51',
  '69',
  'Filial 4',
  '2023-03-12 18:58:06.794203'],
 ['Blush em pó',
  'Eletrônicos',
  '88.99',
  '17',
  'Filial 6',
  '2023-06-22 18:58:06.794203'],
 ['Delineador líquido',
  'Alimentos',
  '1.1',
  '22',
  'Filial 10',
  '2022-10-23 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '58.94',
  '23',
  'Filial 9',
  '2023-04-17 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '76.57',
  '87',
  'Filial 8',
  '2022-12-05 18:58:06.794203'],
 ['Batom líquido',
  'Eletrônicos',
  '22.91',
  '49',
  'Filial 9',
  '2023-07-28 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '28.89',
  '33',
  'Filial 6',
  '2022-09-27 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '33.57',
  '22',
  'Filial 9',
  '2022-09-05 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '4.12',
  '46',
  'Filial 2',
  '2023-08-07 18:58:06.794203'],
 ['Blush em pó',
  'Alimentos',
  '73.13',
  '66',
  'Filial 9',
  '2023-04-23 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '1.69',
  '21',
  'Filial 3',
  '2022-11-20 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '27.18',
  '24',
  'Filial 8',
  '2023-02-01 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '94.47',
  '77',
  'Filial 8',
  '2023-07-03 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '67.19',
  '76',
  'Filial 1',
  '2023-04-10 18:58:06.794203'],
 ['Sombra de olhos',
  'Alimentos',
  '92.72',
  '62',
  'Filial 4',
  '2022-12-08 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '78.29',
  '67',
  'Filial 5',
  '2022-10-09 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '83.18',
  '15',
  'Filial 1',
  '2022-12-21 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '75.77',
  '26',
  'Filial 9',
  '2023-03-07 18:58:06.794203'],
 ['Batom líquido',
  'Roupas',
  '81.71',
  '90',
  'Filial 4',
  '2023-07-25 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '20.73',
  '49',
  'Filial 6',
  '2023-08-11 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '57.12',
  '10',
  'Filial 6',
  '2023-08-11 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '29.61',
  '15',
  'Filial 5',
  '2023-01-24 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '71.75',
  '31',
  'Filial 10',
  '2023-07-26 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Roupas',
  '84.33',
  '26',
  'Filial 6',
  '2022-11-29 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '17.9',
  '33',
  'Filial 7',
  '2023-01-28 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '62.61',
  '34',
  'Filial 6',
  '2023-04-13 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '9.21',
  '95',
  'Filial 10',
  '2023-04-29 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrodomésticos',
  '21.71',
  '77',
  'Filial 2',
  '2022-11-20 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '34.76',
  '51',
  'Filial 4',
  '2023-04-09 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '61.77',
  '41',
  'Filial 3',
  '2023-08-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '29.04',
  '21',
  'Filial 1',
  '2023-04-10 18:58:06.794203'],
 ['Base líquida',
  'Alimentos',
  '32.33',
  '6',
  'Filial 8',
  '2023-05-06 18:58:06.794203'],
 ['Batom matte',
  'Eletrodomésticos',
  '25.68',
  '33',
  'Filial 3',
  '2023-05-24 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '6.8',
  '8',
  'Filial 2',
  '2023-01-19 18:58:06.794203'],
 ['Sombra de olhos',
  'Eletrônicos',
  '85.55',
  '33',
  'Filial 2',
  '2022-10-30 18:58:06.794203'],
 ['Batom matte',
  'Roupas',
  '61.23',
  '80',
  'Filial 6',
  '2023-04-05 18:58:06.794203'],
 ['Corretivo',
  'Eletrônicos',
  '7.43',
  '18',
  'Filial 1',
  '2022-10-27 18:58:06.794203'],
 ['Lápis de sobrancelha',
  'Eletrônicos',
  '92.77',
  '18',
  'Filial 6',
  '2023-02-05 18:58:06.794203'],
 ['Delineador líquido',
  'Eletrônicos',
  '70.44',
  '79',
  'Filial 5',
  '2023-02-19 18:58:06.794203'],
 ['Corretivo',
  'Eletrodomésticos',
  '98.45',
  '14',
  'Filial 7',
  '2022-11-27 18:58:06.794203'],
 ['Delineador líquido',
  'Roupas',
  '12.18',
  '59',
  'Filial 10',
  '2023-07-12 18:58:06.794203'],
 ['Base líquida',
  'Eletrodomésticos',
  '71.31',
  '84',
  'Filial 2',
  '2023-07-19 18:58:06.794203'],
 ['Máscara de cílios',
  'Eletrônicos',
  '54.71',
  '62',
  'Filial 5',
  '2023-06-02 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '45.12',
  '10',
  'Filial 3',
  '2023-04-25 18:58:06.794203'],
 ['Blush em pó',
  'Roupas',
  '32.26',
  '60',
  'Filial 8',
  '2023-03-25 18:58:06.794203'],
 ['Pó compacto',
  'Alimentos',
  '86.78',
  '24',
  'Filial 6',
  '2022-12-13 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '71.86',
  '26',
  'Filial 10',
  '2023-06-02 18:58:06.794203'],
 ['Pó compacto',
  'Eletrônicos',
  '45.38',
  '41',
  'Filial 5',
  '2023-05-25 18:58:06.794203'],
 ['Corretivo',
  'Roupas',
  '53.76',
  '27',
  'Filial 4',
  '2023-03-05 18:58:06.794203'],
 ['Batom líquido',
  'Eletrodomésticos',
  '7.41',
  '93',
  'Filial 6',
  '2023-01-18 18:58:06.794203'],
 ['Batom matte',
  'Eletrônicos',
  '68.97',
  '79',
  'Filial 3',
  '2023-03-15 18:58:06.794203'],
 ['Blush em pó',
  'Eletrodomésticos',
  '10.5',
  '80',
  'Filial 6',
  '2023-07-26 18:58:06.794203'],
 ['Corretivo',
  'Alimentos',
  '67.79',
  '19',
  'Filial 5',
  '2023-09-05 18:58:06.794203'],